### ISSUE TITLE
Set up a development environment

### ISSUE THREAD

**Issue by rossbowen** [GSS-Cogs/dd-cms#1]
After `git clone`-ing the project:

- [x] A dev can buildout to install the Plone backend, for doing Plone development.
- [x] A dev can `yarn start` to run the Volto side, and use a docker container to spin up a basic Plone backend, for doing Volto development. Actually run Plone directly using `plonectl`.
- [x] Explain how to spin up in README.md.

A Plone backend can be spun up, with the Volto plugin applied, using:

```
docker run -p 8080:8080 -e SITE="Plone" -e ADDONS="plone.volto" plone/plone-backend:6.0.0a1 start
```

Further addons can be added using the `ADDONS` env variable, see [`run_plone.sh`](https://github.com/GSS-Cogs/dd-cms/blob/main/run_plone.sh) for an example.

**Comment by ajtucker** [comment]
- [ ] Add separate Dexterity based add-on for SPARQLWrapper and config.

**Comment by cjfairchild** [comment]
@ajtucker to look at pipenv/buildout oddities when trying to build and run the plone-5 docker image.
