### ISSUE TITLE
Define and implement data visualisation content type

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#117]
Design and create a structured content type for charts and their supporting text to enable us to store and re-use charts within the DD-CMS and broader IDS ecosystem.

Aims:

- For representing charts and their configuration within Plone-Volto.

- Ideally should be as generic/abstract as possible so as to be useful outside of the DD-CMS.

- Possible use for a chart library.

To do:

1. Look at existing standards / schemas for representing chart content.

2. Conversation between data engineering, product owner, devs and UX team on structure and flow of charts through the IDS ecosystem

3. Explore technical constraints of Plone-Volto and Plotly in defining this content type

**Comment by nosnickid** [comment]
Create a content type in plone that roughly follows 

https://github.com/GSS-Cogs/climate-change-govuk/blob/028155e6208571e015392af1ca5c173a77cd3c4a/src/types.ts#L16 

 from climate change

**Comment by ajtucker** [comment]
#17

**Comment by ajtucker** [comment]
- [ ] Create content type through-the-web for "figure" as per #17.
- [ ] Look at image content type for how to store props locally in the block.
- [ ] Create content type for chart.

**Comment by charlesons** [comment]
Styling spec for the surrounding chart text captured from slack chat with @gareth-lewis 

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/803140c8-949f-4e79-8454-238971ee2b46)

**Comment by nosnickid** [comment]
https://av.tib.eu/media/54791

**Comment by charlesons** [comment]
Could / should the figure block have a user specified background colour?

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/c71130f8-36d0-4b0e-961a-27a2f3953302)

**Comment by TahaRana97** [comment]
Review with @Alex next week

**Comment by charlesons** [comment]
Duplicate of issue #17

**Comment by charlesons** [comment]
Duplicate of issue #17
