### ISSUE TITLE
Fix duplicate related items issue

### ISSUE THREAD

**Issue by ljcoulson** [GSS-Cogs/dd-cms#121]
Fix the issue shown below with duplicate related articles appearing on load.

![Screenshot 2022-03-02 at 10.54.32.png](https://images.zenhubusercontent.com/61ea86e8ecdfb51ca09a0c1c/3b0eb361-6025-4802-b547-82b461e4f65c)

**Comment by ljcoulson** [comment]
Issue fixed as part of issue 52

**Comment by nosnickid** [comment]
This was merged in #111
