### ISSUE TITLE
Factor out SPARQL data connector

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#14]
Follow https://docs.plone.org/external/plone.app.dexterity/docs/index.html to create a SPARQL data connector content type that implements the eea.api.dataconnector interface/behaviour as per #12, but is in its own package.

We have the ukstats.dev domain for this, do let's use that in the package name, e.g. ukstats.sparql_dataconnector.

Use `mrbob` as per https://docs.plone.org/external/plone.app.dexterity/docs/prerequisite.html#creating-a-package

**Comment by cjfairchild** [comment]
The bootstrap.sh script now incorporates the ukstats.sparql_dataconnector package from the src directory in this Git repository.

**Comment by cjfairchild** [comment]
(See issue-14 branch)

**Comment by TahaRana97** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/GSS-Cogs/dd-cms/14?planning-poker) with ZenHub @ajtucker @anojperera @cjfairchild @rossbowen @nosnickid

**Comment by cjfairchild** [comment]
@ajtucker  and @cjfairchild  to discuss future direction

**Comment by TahaRana97** [comment]
still outstanding, looking to understand whole architecture of plone @ajtucker

**Comment by JasonHowell** [comment]
@nosnickid to try and get it over the line.
