### ISSUE TITLE
Continuous deployment

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#140]
We want to automatically build and deploy the main branch to a staging server when a PR is merged.

Since Jenkins runs on the same host as our staging server, a simple `docker-compose` in a `Jenkinsfile` should be enough.

The `docker-compose` command isn't installed on the Jenkins master node, but the [Docker Compose Build Step plugin](https://plugins.jenkins.io/docker-compose-build-step/) is now installed, so in a Jenkinsfile we should be able to use something like:

```
step([$class: 'DockerComposeBuilder', dockerComposeFile: 'docker-compose.yml', option: [$class: 'StartAllServices'], useCustomDockerComposeFile: false])
```

to bring the services up. We just need to figure out how to build them first.

**Comment by ajtucker** [comment]
I've added a job, https://ci.ukstats.dev/job/GSS_data/job/dd-cms/job/staging/, that should get triggered whenever the `main` branch has finished testing and is green.

It'll run `deploy/deployment-jenkinsfile`, but that won't work because the `docker-compose` command isn't available.

**Comment by nosnickid** [comment]
Hrm, that plugin looks good, but it seems to just shell out to docker-compose:

https://github.com/jenkinsci/docker-compose-build-step-plugin/blob/bff7ba253f1fddf4a688ebbf798d4cef208c30e2/src/main/java/jenkins/plugins/docker_compose/StartAllServices.java#L69

So will the binary need installing anyway?

**Comment by ajtucker** [comment]
> Hrm, that plugin looks good, but it seems to just shell out to docker-compose:

Good spot. Of course, that makes sense.

I'll have a look at getting `docker-compose` into the Jenkins Docker image.

**Comment by ajtucker** [comment]
@nosnickid, getting `docker-compose` into the Jenkins Docker image should be simple. I've got a PR in for it in a separate repo and have tested it out locally. I'll deploy this evening as there'll be some downtime (docker-compose volumes with SELinux require the `:z` suffix to ensure the file context is right and it takes an age to relabel the files on a restart!)

**Comment by ajtucker** [comment]
It appears to work ok, albeit with a minor issue around running as root in the container. I'll do some local testing to see whether this is really necessary.

**Comment by ajtucker** [comment]
This has been working ok for a while, so I'm not sure why we didn't close it earlier.
