### ISSUE TITLE
Support @connector-data in UK stats CSV content type 

### ISSUE THREAD

**Issue by nosnickid** [GSS-Cogs/dd-cms#145]
Extend our CSV content type so that it can produce "@connector-data" format responses.

**Comment by TahaRana97** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/GSS-Cogs/dd-cms/145?planning-poker) with ZenHub @ajtucker @anojperera @charlesons @LeoLeite-ONS @nosnickid

**Comment by nosnickid** [comment]
The blocker on merging this one is that current CSVs use dexterities `container` type, and this change replaces them with a sub class `ICSVMarker`.

The addition of the ICSVMarker interface is what allows me to registrer a specifc ICSVMarker to IDataProvider adapter in zope, so it's a necessary class.

Any current CSV content in plone instances will just be pickled `container`s though, so their `@connector-data` requests will fial. But since the CSVs were useless before - at lesat they couldn't be referenced from chart-builder or anywhere else - we probably don't have any in "prod". 

So rather than wasting time trying to create a migration for content that's probably only present in dev systems, let's just merge this and replace any CSVs that have been created.
