### ISSUE TITLE
Git issues

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#146]
* .gitignore ignores too much esp. plone-5/instance/src
* Where has Huskie hook come from?
* Where have git submodules for volto/src/addons come from?

**Comment by goofballLogic** [comment]
Two candidates for installing husky:
```
./volto/node_modules/react-detect-click-outside/package.json:    "_postinstall": "husky install",
./volto/src/addons/chart-builder/node_modules/react-dropzone/package.json:    "_postinstall": "husky install",
```

**Comment by goofballLogic** [comment]
Looks like husky itself has an "install" script which yarn runs as part of yarn install.
