### ISSUE TITLE
End of discovery phase review/report

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#147]
- [ ] Honest appraisal and recommendations of Plone/Volto to feed into next stage.
- [ ] Issues and limitations of the solution.
- [ ] Presentation / show and tell on everything we've developed for CC & CIS, linking with PMD.
- [ ] Viability of Volto/Plone as a short / long term solution for IDP Dissemination.
- [ ] Features / components that exist and/or have been developed.
- [ ] #192

Note that, as we said right from the start, the emphasis for all this is on delivering working prototypes and code over documentation, so everything we write in the above should be supported by screenshots and explanations of what the prototypes show.

**Comment by TahaRana97** [comment]
@ajtucker held review meeting with darren/rob 14/04/22
