### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#15]
The Climate Change team want to add an overview page with simplified charts showing the latest data from across the various sections of the site.

The charts should be arrayed in columns and provide links to another section or article.

- [x] Install https://github.com/eea/volto-columns-block
- [x] Each chart has the same schema, so look to see whether there's a tile/block we could re-use or whether we need to create a new content type.
- [ ] Create charts as per the https://climate-change.data.gov.uk/ overview page.

**Comment by cjfairchild** [comment]
New content type not necessary - the blocks within the columns use the standard block/page creation interface - one can simply hit '+' and then add a chart or any other block.

**Comment by cjfairchild** [comment]
Creating charts like the climate change overview page -

- I've recreated the grit layout by using 50-50 columns and then populating each column with multiple Plotly charts. The charts stack on top of each other and maintain their spacing naturally.
- The grey styling isn't quite possible like in the overview example page - the 'background' of plotly charts seems to only extent to the axis - not beyond to the labels etc. We might want to adapt the styling somewhere by modifying the plotly charts lib.

**Comment by cjfairchild** [comment]
![Screenshot from 2022-01-11 10-57-54](https://user-images.githubusercontent.com/94971122/148935834-34ac3d97-3947-4ddf-b4de-8210c8720ccf.png)

(Progress so far, all queries using the default query in this library in the Discoconnector patch).

**Comment by TahaRana97** [comment]
Add snapshot of latest front page - this has been completed and can be closed.

**Comment by anojperera** [comment]
This is done as per new design
[Uploading... Screenshot 2022-06-29 at 15.09.35.png]
