### ISSUE TITLE
Gather CSV-W requirements

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#151]
Web publishing requirements:

* CSV-W should be published on the web as two resources: the text/csv resource at some URL, `{A}`, say; the metadata `application/ld+json` (or `application/csvm+json`, or `application/json`) resource at URL `{A}-metadata.json`.
* The URL of the metadata resource may instead be given by a `Link` header as part of the HTTP response to the CSV resource.
* The metadata file should be valid JSON-LD.
* The metadata file should conform to the [Metadata Vocabulary for Tabular Data](https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/).
* ...

Metadata editing requirements:
* User should be able to supply a pre-written JSON metadata file, but this isn't required.
* User can edit standard Dublin Core metadata as usual and this is represented in the JSON-LD metadata.
* User can edit the table schema (columns): titles, descriptions, datatypes.
* User can edit the RDF transformation keys (propertyUrl, valueUrl), with helpers to re-use existing registered properties and fill out valueUrl templates.
* ...

**Comment by anojperera** [comment]
As a first draft of the PR, I've added a field to upload json meta data.

**Comment by anojperera** [comment]
Scoping out few action points to fulfil the requirements of this issue.
- [ ] Able to upload csv
- [ ] Parse csv using csvcube to generate the json-ld metadata
- [ ] Produce editable view of the json-ld metadata.

**Comment by anojperera** [comment]
We've tried to incorporate csvcube as a package to csv content type below are our findings.

- csvcube has a minimum requirement of python3.9
- Plone 5.2 works with python 3.9
- Plone 5.2 constraints.txt describes request package to be version 2.25
- However csvcube requires a request package greater than 2.25.

Two possible resolutions 
- We use plone6
- or possibly explore ways to use csvcube with request 2.25
