### ISSUE TITLE
Volto ADDONS

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#156]
The deployed Volto containers don't seem to be respecting the `ADDONS` env var.

**Comment by nosnickid** [comment]
`ADDONS` env var is a volto 14+ feature.

**Comment by nosnickid** [comment]
Going to create a simple patch to hit `node_modules/@plone/volto/razzle.config.js` to optionally replace `packageJson.addons` to gain it in our instance. Then we can keep the sane env var approach until we upgrade and get it in the formal way.
