### ISSUE TITLE
Add article content type

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#16]
Using Dexterity, create an “article” content type with schema: title; lead paragraph(s); body to include figures.

Use an `<article>` tag to wrap articles in the resulting HTML -- whether this has to be done in React with Volto, or on the Plone side is to be figured out.

These content types can be collected together in a stand-alone ukstats.climate-change.types package.

**Comment by TahaRana97** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/GSS-Cogs/dd-cms/16?planning-poker) with ZenHub @ajtucker @anojperera @cjfairchild @nosnickid @rossbowen

**Comment by cjfairchild** [comment]
Issue not appearing in menu however content is made and in a branch!
