### ISSUE TITLE
Node version requirements for Volto

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#165]
I've been using `nvm` to manage Node versions along with a `.nvmrc` file in the `volto` directory to ensure that my local version of Node is pinned to a consistent version.

Node has always been a moving target and when working on a team project for more than a few weeks, we need to ensure that we're targeting a consistent version across the team.

I had been using the then long-term-support version, `v14.15.1`, but note that a recent package requires a more up to date version, so have now moved to `v14.19.0`.

It'd be worth updating the docs in https://github.com/GSS-Cogs/dd-cms/blob/main/docs/volto.md and also adding a `.nvmrc` file to the `volto/` directory to avoid future devs troubles.

We should also ensure that the `Dockerfile` uses the same version, rather than just the latest `node:14`.

**Comment by edd-harvey** [comment]
@eldeal Is this still applicable?
