### ISSUE TITLE
Add figure content type

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#17]
For this case, we're not sure whether to use Dexterity / Plone, or whether to create a Volto block type, but ether way it would be good to have a "figure" content type with schema:
* title,
* description,
* source(s)
* footnotes,
* a configured plotly chart,
* toggle/checkbox for "inline" or "active" (need to figure out what this is, but it's something to do with whether the title gets prepended with "Figure x" and whether there's an anchor/link)

**Acceptance**
As a member of the climate change team, I can create a figure in some folder or as part of some other content type, filling out the details as above and configuring a data driven chart (e.g. Plotly). I can then add the figure as a block to an article or other page in the site, much as I would add an image to a document.

**Comment by nosnickid** [comment]
We're creating the Chart and Figure content types through-the-web.

Planning to introduce some volto blocks that will be used a custom layout, with appropriate markup and styling, for eg footnotes, source details, etc.

**Comment by ljcoulson** [comment]
PR - https://github.com/GSS-Cogs/dd-cms/pull/139

**Comment by JasonHowell** [comment]
@ajtucker to review.
