### ISSUE TITLE
Add CSV(W) content type

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#19]
Using Dexterity, create a new content type CSV Data allowing the end user to create and upload a CSV file.

Note that this functionality is already covered by the standard "File" content type, though we can automatically add the eea data connected file behaviour and also the administrator can choose whether to allow general "File" uploads or the more specific CSV uploads.

This then unlocks the potential feature to manage some accompanying CSV-W JSON metadata.

**Comment by anojperera** [comment]
I've added the content type. However we probably need to discuss about docker image build for all custom types.

**Comment by nosnickid** [comment]
## Basic CSV create and display cycle

- [] Support upload of a CSVW file into the type
- [] Include the JSON metadata in the "__data" in the Plone view for this - take inspiration from related items
- [] Create a volto layout view for CSVW that understands the CSVW metadata and shows some interesting fields

**Comment by ajtucker** [comment]
Closing this as the original intent has been implemented in #107. Let's raise a new issue for the above points from @nosnickid and arrange for a session on designing the next steps.
