### ISSUE TITLE
Investigate upgrade path to Plone 6

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#199]
After delays due to a pandemic, Plone 6 is [due to be released](https://plone.org/download/release-schedule) in the second quarter 2022.

[Volto 15.0.0 for Plone 6](https://plone.org/news/2022/volto-15-0-0-released) was released last month.

We need to prepare for this major version change by testing our plugins and addons in advance.

- [ ] Set up separate Docker images for Plone 6 and Volto 15.0.0
- [ ] Deploy and test.

**Comment by TahaRana97** [comment]
Please include DOD
