### ISSUE TITLE
Remove mrs-developer version of chart-builder and rely on an NPM release of it

### ISSUE THREAD

**Issue by nosnickid** [GSS-Cogs/dd-cms#200]
`chart-builder` uses `react-scripts` for its direct dev environment.

When we use `mrs-developer` to add `chart-builder` to `dd-cms`, we have to register it as a yarn workspace to ensure it is handled in the right way by the babel loader in webpack in the `dd-cms` dev stack.

One feature of workspaces is the top-level project pulls the dependencies from them. This means `chart-builder` tries to bring in `react-scripts`, and its `webpack@5` dep, which conflicts with the `webpack@4` dep from `dd-cms`

We made a branch in `chart-builder` that just dropped its dev environment when we first integrated it. But it's getting to be a pain keeping the various versions in sync.

The fix is to package chart-builder up as a regular NPM module and then depend on known releases of it, keeping dev on chart-builder and the integration separate.

Issue https://github.com/GSS-Cogs/chart-builder/issues/85 tracks creation of the NPM library.

This issue tracks migration dd-cms to using it.

Definition of done; our volto-chart-builder extension depends on the NPM gss-cogs-chart-builder and the mrs-developer reference to chart-builder has been removed, but we still have a rapid development cycle available.

Acceptance criteria: 

- [ ] charts still render in Volto after merging the PR
- [ ] Hot module reloading is still possible when developing the integrated chart-builder

**Comment by nosnickid** [comment]
Re progressive enhancement, this should with help the large JS bundle

**Comment by edd-harvey** [comment]
@mikeAdamss found this ticket in refinement session, is this still valid? Or can we bin it?
