### ISSUE TITLE
Extend Log in / Log out functionality

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#208]
- [x] Add a Log out button that shows when the user is logged in
- [x] For CC2 locate the login / logout as a link in the footer similar to:

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/fa1e3f3d-9859-47c9-b26e-65ff50a37284)

**Comment by ajtucker** [comment]
In the first instance, we put the login link in the footer and remove the button in the header.

**Comment by ajtucker** [comment]
With Unit Tests (TM)
