### ISSUE TITLE
Remove the volto-plotlycharts add-on from Volto

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#212]
Remove the volto-plotlycharts add-on for the following reasons:

- No longer needed as volto-chart-builder provides charting functionality 
- Avoid potential confusion for users over which chart block type to select
- Decrease bundle size

Definition of done:

- [x] References to volto-plotlycharts removed from code
- [x] Plotly charts block option no longer appears in the UI

Acceptance criteria:

- [x] Climate-1 site continues to function correctly

**Comment by nosnickid** [comment]
The deploy for this failed https://ci.ukstats.dev/job/GSS_data/job/dd-cms/job/staging/31/console

I'll take a look into why
