### ISSUE TITLE
Error / shutter pages

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#225]
4xx and 5xx pages should follow gov.uk service design patterns:

- [ ] [There is a problem with the service (500)](https://design-system.service.gov.uk/patterns/problem-with-the-service-pages/)
- [x] [Page not found (404)](https://design-system.service.gov.uk/patterns/page-not-found-pages/)

**Comment by JohnLewisUR** [comment]
Some information guidance available on the GOV.UK design system.
404 complete and the rest in progress.

**Comment by StRhys** [comment]
Currently includes Lorem ipsum on ServiceProblem view.
I've also updated the styling and wording on error views for 401 and 403 status.
