### ISSUE TITLE
CC v2 alpha

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#226]
Release a minimally working version of the newly styled Climate Change website to alpha-v2.climate-change.data.gov.uk, with the usual blanket HTTP Basic Auth.

We expect to put this in front of friendly users for feedback.

**Comment by peterfrenchons** [comment]
Have reviewed this Epic now we have reached the point of doing user research and presenting to key audiences (advisory group and data bites).
As of now there is one item #327 which is not yet started, but does not actually form part of the core product of the Climate Change portal website.
Recommend closing as complete as MPV for the purposes stated

**Comment by peterfrenchons** [comment]
Agreed to close and generate new Epic to cover all remaining actions beyond on this ticket to bring together all activities that need to happen to have v2.0 replace v1.x

**Comment by peterfrenchons** [comment]
New Epic raised - [#23](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gss-cogs/ukstats.ccv2.theme/23)
