### ISSUE TITLE
Decide on the domain name (alpha-v2.climate-change.data.gov.uk)

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#234]

**Comment by TahaRana97** [comment]
Everyone agrees with domain name

**Comment by ajtucker** [comment]
After Friday's meeting, we propose:
* staging.climate-change.data.gov.uk is the site we'll continuously deploy the main branch of the CMS based Climate Change site to, CCv2.
* beta.climate-change.data.gov.uk will stay as the site we continuously deploy the main branch of the Svelte based Climate Change site from last year, CCv1.
