### ISSUE TITLE
Navbar caches top level content items

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#268]
I've noticed that the list of top level content items shown in the navbar seems to lag behind what the user should see, e.g. removing items or excluding them from navigation, logging in and out, the page needs to be refreshed or the user needs to click on a link before the navbar items are updated to show what the current user should see.

**Comment by eldeal** [comment]
related, possible duplicate: https://github.com/GSS-Cogs/dd-cms/issues/455
