### ISSUE TITLE
Articles list page

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#290]
Look at how to enable the cc_preview view on a folder, or whether we just use a page with sub pages.

**Comment by charlesons** [comment]
WIP using an adapted copy of the Volto SummaryView component:

https://github.com/GSS-Cogs/dd-cms/commit/d7b42070cfacc7c31485239e39f57504fb94841e

**Comment by anojperera** [comment]
Whats remaining to do
- [ ] Style corrections
- [ ] Related Links
- [ ] User name translations
