### ISSUE TITLE
Use staging SPARQL endpoint

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#299]
We're currently using the beta.gss-data.org.uk endpoint, but should switch to staging.gss-data.org.uk while we're testing things out.

**Comment by nosnickid** [comment]
Hrm, yeah I see that now. It must just be that the data we're querying isn't there on staging, and then when trying to manually check it got confused.

**Comment by charlesons** [comment]
Ticket seems to have been completed in #304
