### ISSUE TITLE
Volto Docker image size

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#310]
The `yarn install` step in the Dockerfile for Volto creates a 2.5GB layer in the resulting Docker image.

1.2GB or so appears to be `yarn` cached downloads under `/usr/local/share/.cache/yarn`, which we can do away with if we use a multi-stage build.

`/root/.cache` also has 735MB of Cypress node packages.

Then `/app/node_modules` is another 1.2GB with `@storybook`, `plotly.js`, etc.

Question (@nosnickid): does the Razzle build put everything needed under the `build` directory if we ensure that `extensions` doesn't include the `node_modules` directory in `razzle.config.js`?

**Comment by nosnickid** [comment]
I'll have to look at the bit about the `extensions` dir excluding
`node_modules`. At the moment, we definitely need the `node_modules` dir
for the `yarn start:prod` to run (the express http server).

**Comment by nosnickid** [comment]
I took a look at this. The server definitely still needs the `node_modules` dir to run `yarn start:prod`. So I'll put a little PR together that includes a `yarn cache clear` to at least tidy up the yarn cache.
