### ISSUE TITLE
Dashboard tile source

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#327]
Tweak the dashboard tile to include a user specified source as per Figma design

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/151c4638-d8b9-4015-a17b-4e46a6f46c4d)

- [ ] A single user specified source label and link text

A future design iteration will provide a solution for multiple sources at a later date after UR / feedback

**Comment by ajtucker** [comment]
For now look into adding simple text block schema so that it can have text and links etc. but if not possible, just keep it simple with a layout schema.

**Comment by charlesons** [comment]
@gareth-lewis reviewed the ticket and refers the question on Dashboard tile source back to CC team

**Comment by charlesons** [comment]
Cross checked with @peterfrenchons and the steer is that this ticket isn't priority for now. Moving to product backlog.

**Comment by eldeal** [comment]
No UR suggesting a need for this
