### ISSUE TITLE
Content for example article 'UK Climate is changing' 

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#338]
- [x] Create SPARQL queries for charts and map data
- [x] Create charts and maps
- [x] Create figures for charts and maps
- [x] Create styled text content
- [ ] Update page links
- [ ] Proof read

**Comment by charlesons** [comment]
Text styling is inconsistent between edit and view modes, so not WYSIWYG

Edit mode - body text is 14px:

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/a686089e-a804-440d-aa4e-57de7b59879d)

View mode - body text is 16px:
![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/6a163d79-7a8f-4236-9ddb-d1b420b7bbde
)

**Comment by charlesons** [comment]
Largest available text size in the slate editor (using H1) is 31.5px vs 36px in Figma design

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/ae3e2dc5-803a-4be4-8fea-cfb67421c044)

**Comment by charlesons** [comment]
Medium heading size (h) is 21px vs 24px in Figma design

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/ddd7ce12-3d71-40ae-b602-8d058ab75d52)

**Comment by charlesons** [comment]
Issue #340 - recent articles list duplicates on each edit-save cycle

**Comment by charlesons** [comment]
Should the dashboard masthead background colour extend only to the width of the page?

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/28207db4-49a6-4fef-ba04-381bb0aa1ea1)

**Comment by charlesons** [comment]
Adaptation sub heading was potentially set at the wrong size (h3) in CCv1. Have set it as h2.

**Comment by charlesons** [comment]
Figure blocks without a summary include the text 'Text' whereas the element should not render at all. 

Issue #341 created to fix

**Comment by charlesons** [comment]
According to the Figma design articles should be able to have multiple authors. Is this currently possible within Volto?

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/2feca649-766a-4635-84c7-8c0d7f7a703e)

**Comment by charlesons** [comment]
In CCv1 the article "The UK's climate is changing..." has a link in the leading paragraph to the latest report from IPCC

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/c36adf5e-2722-4975-b890-e67faab40e9f)

**Comment by charlesons** [comment]
Suggestion - remove the default SPARQL query text when creating a new SPARQL Data Connector. 

Removing it manually each time is an additional step for the user.

**Comment by charlesons** [comment]
Unable to load data for Figure 3: UK growing season length in days, 1960 to 2020 from PmD on either beta or staging endpoints using SPARQL Data Connector.

Note the data loads using the tool at https://beta.gss-data.org.uk/tools/sparql

```
PREFIX qb: <http://purl.org/linked-data/cube#>
            PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
            PREFIX scovo: <http://purl.org/NET/scovo#>
            PREFIX mes: <http://gss-data.org.uk/def/climate-change/measure/>
            PREFIX dat: <http://gss-data.org.uk/data/gss_data/climate-change/met-office-annual-growing-season-length-with-trends-actual#>
            PREFIX dim: <http://gss-data.org.uk/data/gss_data/climate-change/met-office-annual-growing-season-length-with-trends-actual#dimension/>
            PREFIX geo: <http://gss-data.org.uk/data/gss_data/climate-change/met-office-annual-growing-season-length-with-trends-actual#concept/geography/>
            
            PREFIX data: <http://gss-data.org.uk/data/gss_data/climate-change/met-office-annual-growing-season-length-with-trends-actual#>
            PREFIX meas: <http://gss-data.org.uk/def/climate-change/measure/>
            
            SELECT*
            {
            
                        {
                          SELECT ?year ?geo_label ?total
            
                                WHERE {
                                          ?obs qb:dataSet dat:dataset ;
                                                 mes:annual-growing-season ?total ;
                                                 dim:year [ scovo:min ?year_start ] ;
                                                 dim:geography ?geo .
                                          FILTER (?geo in (geo:uk, geo:uk-trend))
                                          ?geo rdfs:label ?geo_label .
                                          BIND(YEAR(?year_start) AS ?year)
                                        }
            
                        }
            
                        UNION 
                            {
                                # Long term average between 1981 and 2010
                                SELECT DISTINCT ?geo_label ?year ?total
                                WHERE {
                                    ?obs qb:dataSet data:dataset ;
                                        dim:year [ rdfs:label ?year ];
                        
                                    BIND("1961 to 1990 long-term average" AS ?geo_label)
                        
                                    {
                                        SELECT (ROUND(AVG(?value)*10)/10 AS ?total)
                                        WHERE {
                                            ?obs qb:dataSet data:dataset ;
                                                    meas:annual-growing-season ?value;
                                                    dim:year [ rdfs:label ?year ];
                                                    dim:geography [ rdfs:label ?geo_label ];
                        
                                            FILTER(?geo_label = "UK") .
                                            FILTER(?year >= "1961" && ?year <= "1990") .
                                        }
                                    }
                                }
                            }
            
                        UNION
             
                            {
                                # Long term average between 1981 and 2010
                                SELECT DISTINCT ?geo_label ?year ?total
                                WHERE {
                                    ?obs qb:dataSet data:dataset ;
                                        dim:year [ rdfs:label ?year ];
                        
                                    BIND("1981 to 2010 long-term average" AS ?geo_label)
                        
                                    {
                                        SELECT (ROUND(AVG(?value)*10)/10 AS ?total)
                                        WHERE {
                                            ?obs qb:dataSet data:dataset ;
                                                    meas:annual-growing-season ?value;
                                                    dim:year [ rdfs:label ?year ];
                                                    dim:geography [ rdfs:label ?geo_label ];
                        
                                            FILTER(?geo_label = "UK") .
                                            FILTER(?year >= "1981" && ?year <= "2010") .
                                        }
                                    }
                                }
                            }
            }
            
            ORDER BY ?year ?geo_label
```

**Comment by charlesons** [comment]
Figures are all now created. May be good to tweak series colour assignments for some charts.

Remaining tasks are to set the internal links from the article text to the figures and to proof read the article.

Note - the issues raised in the comments above need also to be processed and tickets created in some cases.

**Comment by charlesons** [comment]
Attempted to create internal links but they seem not to take any effect. Need to look deeper into the docs to understand the functionality in Volto.

**Comment by charlesons** [comment]
@peterfrenchons would you like to do the proof reading part?

**Comment by peterfrenchons** [comment]
Email sent to Tom S for him to proof read and make any corrections. If anything there he cannot handle he should contact me to arrange. Waiting until end of this week for normal action, and will chase up on CC standup on Monday if no positive response.

**Comment by peterfrenchons** [comment]
Link to figure 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12 not in v2.0 but question if needed anyway?
Figure 1 2020 label missing and hover text to include year

Figure 2 2020 label missing and hover text to include year

Figure 3 2020 label missing and hover text to include year

Figure 4  hover text to include year

Figure 5 Coal and Other Fossil fuels have been combined.  Hover text to include year. 2020 label missing

Figure 6 has a link from text but straight to live page. Not sure if will be an issue. Hover text to include year and 2020 label missing

Text before figure 7 has inconsistent capitalisation. One for CC team to decide on

Figure 7 2020 label missing and hover text to include year

Under Adaptation, Woodlands heading is missing

"semi-natural habitats" link goes to 404. Also issue on current live

"benefits from natural trees" link on v2.0 incorrect. v1.1 is ok

"UK covered by woodland" link wrong on v2.0. v1.1 is ok

Figure 8 - need separate UK data series, and sort out hover text plus add year

Figure 10 - reversed colours. hover text removed Total and add year

Figure 11 - bars stacked in opposite way to v1.1. Hover contains a Total that is not on v1.1. Legend shown at bottom rather than at top as in v1.1

Figure 12 - Y axis label truncated. X axis labels with different view vs v1.1. Hover text to include year

**Comment by peterfrenchons** [comment]
Created new card for QA items #25
