### ISSUE TITLE
Super header should programatically populate articles and dashboard sections

### ISSUE THREAD

**Issue by rossbowen** [GSS-Cogs/dd-cms#348]
[`getNavigation()`](https://github.com/plone/volto/blob/master/src/actions/navigation/navigation.js) has a depth parameter.

We might be able to adopt some of the patterns applied in the [vanilla Volto `Navigation` component](https://github.com/plone/volto/blob/master/src/components/theme/Navigation/Navigation.jsx#L188-L198).

```js
export default compose(
  injectIntl,
  connect(
    (state) => ({
      token: state.userSession.token,
      items: state.navigation.items,
      lang: state.intl.locale,
    }),
    { getNavigation },
  ),
)(Navigation);
```

**Comment by eldeal** [comment]
possible duplicate https://github.com/GSS-Cogs/dd-cms/issues/455
