### ISSUE TITLE
Plone authentication

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#39]
We're aiming to use OpenID Connect along with a provider like auth0 to manage user access to the various web services, including the various CMSs that we will host.

Plone has a pluggable authentication mechanism (PAS) that allows for users and roles/groups to be managed in any number of local or external systems. There is a package for OpenID Connect, although it is meant to be more of an identity provider than a consumer and hasn't been worked on for a few years. The closest appears to be pas.plugins.authomatic, though this will need some work too.

In the meantime, it would be useful to see whether there's a way to use either GitHub or Google with OAuth2.

**Comment by TahaRana97** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/GSS-Cogs/dd-cms/39?planning-poker) with ZenHub @ajtucker @anojperera @cjfairchild @nosnickid @rossbowen

**Comment by cjfairchild** [comment]
@ajtucker created a branch so far :)

**Comment by ajtucker** [comment]
We've tested this with our Google domain, gsscogs.uk. Domain users can login using Google as an OAuth 2.0 provider and be registered in the CMS, from where they can be assigned roles etc.

Configuration is documented in the PR #86 .
