### ISSUE TITLE
Secure CMS Architecture

### ISSUE THREAD

**Issue by JasonHowell** [GSS-Cogs/dd-cms#398]
To understand and produce a secure architecture for the dissemination of secure data/content that integrates with the current PMD secure architecture.

**Comment by ajtucker** [comment]
In order to assure some service deployment, the architecture of the deployment needs to be declared, so I've added a dependency on the Kubernetes based deployment to be used for Climate Change v2.

This will give us something concrete to understand the security boundaries.

**Comment by eldeal** [comment]
Rob T: Need something in place by Dec 7th
Suggestion to convert to epic and add tasks following CATD convos

**Comment by edd-harvey** [comment]
Currently not needed
