### ISSUE TITLE
gov.uk styling

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#4]
As a user of the CMS I expect the service to look and feel like GOV.UK so that I know it is an official site.

There is a [govuk-react](https://github.com/govuk-react/govuk-react) we can make use of to see whether the Volto components can be implemented with these govuk-react components.

**Comment by ajtucker** [comment]
- [ ] Override nav component to show the articles and pages.
- [ ] Style the nav component / layout.

**Comment by anojperera** [comment]
Is this in a shape to close the item?
