### ISSUE TITLE
About Article 

### ISSUE THREAD

**Issue by TahaRana97** [GSS-Cogs/dd-cms#427]
confirm with osamede/shannon to execute

**Comment by Shannon95** [comment]
https://staging.climate-change.data.gov.uk/about

**Comment by charlesons** [comment]
Issue [#442](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gss-cogs/dd-cms/442) created for the remaining styling requirements to match the Figma design

**Comment by peterfrenchons** [comment]
Read through the article on staging and no issues found. There will be a further QA of pages once styling has settled and move closer to getting pages public facing
