### ISSUE TITLE
Implement hotjar/google analytics/cookies is integrated into 2.0 portal

### ISSUE THREAD

**Issue by TahaRana97** [GSS-Cogs/dd-cms#428]

**Comment by JohnLewisUR** [comment]
Have set up a new 'property' with Google Analytics for climate-change.data.go.uk/ and have the following information to share:
![image.png](https://images.zenhubusercontent.com/5d93561ee39efb000125536d/77c1b908-7679-4029-b761-256a3bd662e9)
