### ISSUE TITLE
QA of Emissions Dashboard

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/dd-cms#438]
- [x]  Chart 1. Set Y axis range as 0 - 1000
- [x]  Chart 2. Letters in chemical formulae in legend to be capitals
- [x]  Chart 2. Move legend (view seems to be covering x axis labels) and adjust layout so legend labels do not overlap
- [x]  Chart 3.  Set Y axis range as 0 - 200
- [x]  Chart 4.  Y labels truncated in some cases. NB if not a simple quick fix then leave as it is and we fix it later
- [x]  Chart 5 (Map).  The font for chart notes inconsistent. NB if not a simple quick fix then leave as it is and we fix it later
- [x]  Chart 6.  Set Y axis range as 0 - 250

**Comment by charlesons** [comment]
Chart 5 (Map) - replaced earlier version of the map based on earlier figure block component

**Comment by charlesons** [comment]
For the last item _Chart 6. Set Y axis range as 0 - 250_ - couldn't replicate any issue with the range.

**Comment by charlesons** [comment]
Leaving ticket open for @peterfrenchons to review tomorrow

**Comment by charlesons** [comment]
Update on the last item Chart 6. Set Y axis range as 0 - 250 - this appears to have self resolved. Also we have found on other charts that missing end of axis labels can be coerced into showing by adding some additional margin - which Plotly then takes advantage of to show the missing label. Also changing the Axis Type in the newly introduced feature in issue #129 can also help tweak the displayed axis labels.

**Comment by JasonHowell** [comment]
Two tickets have been created:
- adapted the API connectors
- produce the sqarql query.

**Comment by peterfrenchons** [comment]
Chart 4 still truncating the longest strings. Consider reduced font size (looks like this is how current portal handles this issue)?

**Comment by peterfrenchons** [comment]
Chart 6 may need margin reviewed? label 250 still not showing on my ONS laptop.....

**Comment by peterfrenchons** [comment]
QA issues for Charts 4 and 6 need another look please. @osamede20 @Shannon95

**Comment by peterfrenchons** [comment]
Feedback on Charts 4 and 6 need another look as don't seem to be fully sorted. Adding to ticket #426 as that is an active ticket.

**Comment by peterfrenchons** [comment]
Closing this as done apart from the two issues transferred
