### ISSUE TITLE
Create version of v2.0 CC portal for use at Data Bites

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/dd-cms#439]
Following pages need to have been completed incl updates from QA comments, and "published":

- [x] https://staging.climate-change.data.gov.uk
- [x] https://staging.climate-change.data.gov.uk/articles
- [x] https://staging.climate-change.data.gov.uk/articles/the-uk-climate-is-changing
- [x] https://staging.climate-change.data.gov.uk/dashboards/emissions

Once completed, create a snapshot copy of the site on a different URL, password protected.

**Comment by JasonHowell** [comment]
Just waiting for Tom to confirm that he's baseline his slide deck.
