### ISSUE TITLE
Horizontal scrollable dashboard tiles on mobile viewports 

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#441]
Check feasibility of implementing horizontal scrollable dashboard tiles as below on mobile

https://images.zenhubusercontent.com/445470605/071b4861-480a-4627-9ffa-c0763e62bd2c/screen_recording_2022_06_30_at_10_32_18.mov

**Comment by charlesons** [comment]
Keep in product backlog until go ahead given by @gareth-lewis or @JohnLewisUR

**Comment by edd-harvey** [comment]
@gareth-lewis - is this still needed?
