### ISSUE TITLE
Analyse staging site and Jenkins pipeline outage on 01/07/2022

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#444]

**Comment by ajtucker** [comment]
When I went to look, the journal had already been rotated (old entries removed), so we missed what happened here.

The VM hosting Jenkins and other sites, including staging.climate-change.data.gov.uk, currently has a 10GB boot disk for Fedora CoreOS where the logs are stored. The default log retention policy is to use max 10% of the disk, so 1GB logs. For this VM with many Docker containers and invocations, it doesn't take long to use 1GB.

I'd recommend a separate, consolidated logging service, and at this point, just using the standard Google container optimised OS where I'd imagine this is the default. We used Fedora CoreOS to mitigate against running the VM in another cloud.

There was another more recent outage where I did manage to scroll through the logs and in this case, an out-of-memory exception was raised and the kernel killed off a process (chrome). This seems to render the machine unstable and it needed restarting via the cloud console.
