### ISSUE TITLE
Restore or recreate Adaptation dashboard 

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#445]
The Adaptation dashboard content became disconnected from the site navigation whilst implementing issue #290. 

There is a backup of the Adaptation dashboard still present in the CMS so we can restore it from there once the site freeze for 6th July is over. 

We may also want to recreate the figures as the figure block schema has changed significantly since this content was created.

**Comment by charlesons** [comment]
Replacing existing charts as they have inconsistent styling of the source and notes text in the figures.

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/d4c95473-a29a-4b3f-9b50-52ebd5f97681)t

**Comment by charlesons** [comment]
Comparison old to new of the Index of pollinators chart

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/ee004238-fb4b-4cb6-9edf-bda770c15d53)

**Comment by charlesons** [comment]
Dashboard recreated and ready for review: 

https://staging.climate-change.data.gov.uk/dashboards/adaptation

Note there is a pending task of cleaning up the backup versions of the dashboard in Plone

**Comment by peterfrenchons** [comment]
QA on this page will be done separately. Page working and all charts exist
