### ISSUE TITLE
Login form text should be 19px

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#450]
- [ ] The 'Login' text
- [x] The 'Select Login Provider' text

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/23c1fc11-6344-4e75-a73f-4881f51eb3ad)

**Comment by StRhys** [comment]
This is a fairly old ticket, it might be worth a new one to bring it more inline with the [Figma designs](https://www.figma.com/file/wyGSTuYr2JUi0jauLvQtAe/%E2%9C%8F%EF%B8%8F-Content-Management-System-(CMS)?type=design&node-id=818-5211&t=NwqG2tpIKD7dI7dR-0) at some point.

**Comment by eldeal** [comment]
PR approved, can be merged and tested in Staging

**Comment by edd-harvey** [comment]
has this been merged into staging?
