### ISSUE TITLE
CCv2 Components from Figma design

### ISSUE THREAD

**Issue by nosnickid** [GSS-Cogs/dd-cms#47]
Recreate designs in CCv2 Figma as static pages in React, broken down into components that are statically populated, but with an eye towards dynamic content in a later ticket.

**Comment by nosnickid** [comment]
Recreate components in https://www.figma.com/file/n61a8x7kKnkriF7b9XAADl/Climate-Change?node-id=813%3A7829 in a plone extension

**Comment by nosnickid** [comment]
This is ready to merge, I think it's a good idea for me and Alex to put some idea together for how to demo in the 3 week sprin

**Comment by TahaRana97** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/GSS-Cogs/dd-cms/47?planning-poker) with ZenHub @ajtucker @anojperera @cjfairchild @nosnickid @rossbowen

**Comment by nosnickid** [comment]
This is merged and the v2 components are now being made dynamic in #54, and we have the climate-1 and climate-2 deployments running with the relevant addons included.
