### ISSUE TITLE
Remove DISCODATA connector as no longer required

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#478]

**Comment by StRhys** [comment]
The discodata connector gets registered by the `eea.api.dataconnector` add-on, and we are using this within our sparql and csv types. As well as using discodata for their `contentTypesViews`, so I have removed it from being available on the front end.
Plone->climate-change->portal_types->discodataconnector->Implicitly addable? == false
![image.png](https://images.zenhubusercontent.com/62f20b9a8dde10123518450a/391b1493-a82e-4b77-86d6-6be645e5fbc2)

I have also removed it being selectable as a type in some widgets and chart builder edit

**Comment by eldeal** [comment]
PR approved, can be merged and tested in Staging

**Comment by edd-harvey** [comment]
has this been merged into staging?
