### ISSUE TITLE
Want to change Article "Emissions embedded in trade...." Figure 3 from image to dd visualisation

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/dd-cms#487]
Currently an image on the CC portal. 

The CC team want to change this to a dd visualisation to enable future updates to be made using the data.

Note from Bec:
Figure 2 data is already on the datastore:
https://beta.gss-data.org.uk/cube/about?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-trade-in-goods-catalog-entry (and this should be the same data needed for Figure 3). 

Note from PF - added 05/09
All the data to create these charts are available here: 
Exports - https://www.ons.gov.uk/visualisations/dvc1515/treemap/exports.xlsx
Imports - https://www.ons.gov.uk/visualisations/dvc1515/treemap/imports.xlsx
It looks like the images we created are copied from https://www.ons.gov.uk/economy/nationalaccounts/balanceofpayments/bulletins/uktrade/july2021

**Comment by charlesons** [comment]
Of the current six plots included in figure 3, two should be possible using chart builder's current capability.

Some changes and additions to CB functionality are required for the following


Treemap visualisation [Issue #136](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gss-cogs/chart-builder/136) created
