### ISSUE TITLE
Publisher wants to use increased amount of series/categories without warning message

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/dd-cms#488]
Although it is a warning and does not stop publisher completely, we should review the limits currently set and consider allowing publisher to use a higher number with better UX

Feedback from Bec 19/07

**Comment by charlesons** [comment]
Holding off development on this and will await further UR input to confirm the requirement.

**Comment by JasonHowell** [comment]
This is nearly a year old and hasn't come up again, so closing ticket.
