### ISSUE TITLE
Automated backup and recovery on GKE

### ISSUE THREAD

**Issue by JasonHowell** [GSS-Cogs/dd-cms#489]
**Backup:** 

- [x] Cron job to do nightly snapshot backup of ZODB and blob storage from the data volume on staging.climate-change.data.gov.uk to a google bucket using gsync

**Recovery:**

- [x] Written recovery procedure
- [ ] Scheduled recovery tests

**Retention policy:**

- [ ] Check with CC team and decide on policy

**Comment by JasonHowell** [comment]
Understand the back up strategy and the recovery procedure for the CMS components. 

Daily incremental
Full weekly back-ups

**Comment by TahaRana97** [comment]
@rossbowen is it a blocker for going to live - or a nice to have?

**Comment by rossbowen** [comment]
I think we need some form of disaster recovery, just in case!

**Comment by anojperera** [comment]
I've looked into using GKE persisted storage on the data folder in plone.

**Comment by eldeal** [comment]
This can be deprioritized for now. We have a manual, documented recovery strategy and plan to move to a Managed cloud DB but the managed DB is not urgent and it would be preferable to have a solid IAC foundation in place to build that managed DB on top of.

**Comment by mikeAdamss** [comment]
mechanics have changed a bit as our stack as evolved, but this is mostly done (will be fully done when production env is on)

backups of cloud sql are nightly by default, have set retention to 14 days but that was just an arbitrary choice, can alter easily enough given a steer.

**Comment by eldeal** [comment]
Closing this, it will be avaailalble when #787 is complete but there is no specific work left to do here
