### ISSUE TITLE
Investigate flushing redux store on logout to maintain accurate application state for authorisation state

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#491]
Logged in state

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/3499fe5a-97cf-4a6f-81e4-9cf8a31f3857)

Logged out state without refreshing

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/645486f8-16c7-4cba-8017-be14c3cca893)

After refreshing (logged out)

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/7309a0c5-05cf-42eb-a006-5b539186259f)

**Comment by JasonHowell** [comment]
This can be closed as a bug.
