### ISSUE TITLE
Implement dashboard menu summaries

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#492]

**Comment by TahaRana97** [comment]
@charlesons @anojperera catch up with alex on this next week

**Comment by charlesons** [comment]
The task is to show the dashboard summaries in the dashboards menu - as per Figma

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/3157e499-27d2-45c0-bee5-7052704a7f8b)

**Comment by JasonHowell** [comment]
This has been implemented as per design. Closing.
