### ISSUE TITLE
Remove CC_preview_2 view

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#494]
- [x] Confirm the view isn't in use
- [x] Remove the component
- [x] Update the Volto config

**Comment by JasonHowell** [comment]
Still outstanding and a low priority.

**Comment by StRhys** [comment]
Removed `cc_preview2` from the Available view methods on both the Document and Folder types in the plone/zope interface. I have also removed `cc_preview2` from the volto config file and its associated component.

**Comment by eldeal** [comment]
PR approved, can be merged and tested in Staging

**Comment by edd-harvey** [comment]
Has this been merged into staging?
