### ISSUE TITLE
BDD tests of mobile responsive site 

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#501]
Minimal acceptance test:

- [ ] Front page loads correctly at mobile and tablet viewports (menu, featured article, dashboard tiles, article list, related links)
- [ ] Navigate to an article and the article loads correctly

**Comment by ajtucker** [comment]
See also #506

**Comment by JasonHowell** [comment]
Closing to raise a ticket about our testing approach.
