### ISSUE TITLE
Video demo showcasing the new Climate Change portal in DD CMS

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#502]

**Comment by TahaRana97** [comment]
meeting with darren, charles, anoj 26/07

**Comment by TahaRana97** [comment]
pending feedback with @JasonHowell @peterfrenchons @anojperera @charlesons

**Comment by JasonHowell** [comment]
Show n tell arranged for Tuesday 8th with the CIS stakeholders.
