### ISSUE TITLE
Overall Workflow

### ISSUE THREAD

**Issue by JasonHowell** [GSS-Cogs/dd-cms#504]
This is a spike to understand what is required in overall workflow/process/policy's of the CMS to:

- IDS 
- Wanda Journey
- SLAM (Starter, Leavers and Movers)
- Backup and recovery policy
- Dataset housekeeping policy

**Comment by AshleyONS** [comment]
[IDSD Processes](https://officenationalstatistics.sharepoint.com/:u:/r/sites/digpub/DigPub/IDS%20Dissemination/Business%20Analysis/Edd%20Harvey%20-%20WIP/BA_IDSD-All%20Processes_01.vsdx?d=wf37c9a709b024f1091b0b07d049fcde8&csf=1&web=1&e=4KIC4T)
[Wanda Journey](https://miro.com/app/board/uXjVOcyi_kw=/)
