### ISSUE TITLE
Spike: Dataset lifecycle and version management

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#505]
Spike to meet the following goal defined by the product owner:

**_Need to understand about static / dynamic articles? Conversations have gone on about the need for Articles which reflect a point in time (not updated as the data updates) as well as the dynamic form we sort of delivered for the current portal._**

- [ ] What is the current behaviour the CMS when a dataset is updated or changed? Does the content update? Is the behaviour consistent for CSV and SPARQL sources? Does the publication state of data connectors have any effect on their ability to update the consuming content? 
- [ ] What processes are in place or under consideration for managing the lifecycle of datasets?
- [ ] Is there any existing specification to conform to from the Wanda journey, user research or design?
- [ ] How can dataset versions be clearly presented to users (both readers and editors)

@rossbowen has written the following on the topic:

https://github.com/GSS-Cogs/sprint-planning/issues/2
https://github.com/GSS-Cogs/application-profile#versions (edited)

**Comment by ajtucker** [comment]
See also #581

**Comment by eldeal** [comment]
Once PMD manages data versions we'll need to take another look at how we interact with those versions
