### ISSUE TITLE
Mobile view front page margins

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#506]
Designs for mobile on the front page remove the globe and have the masthead text full width:

![image](https://user-images.githubusercontent.com/261235/180402405-24696f85-41e5-4989-ad41-4c73f39e7aad.png)

However, the current render on mobile looks like this:

![image](https://user-images.githubusercontent.com/261235/180398849-90c907da-1db0-4e05-b197-5d112bb1cfe9.png)

**Comment by ajtucker** [comment]
It'd be good to have some BDD coverage for this too, starting something like:

```gherkin
Feature: Mobile / responsive

  As an end user on a mobile device I can still access all the pages, read the text and use the charts.

  Background:
    Given I open the url "http://climate-change.data.gov.uk/" with device "iPhone X"
    And I expect the element "#main" is visible

  Scenario: Front page on mobile
    Then I expect the element "img.app-masthead__image" is not visible
    ...
```

**Comment by charlesons** [comment]
Checked this on mobile and the issue seems to be resolved (most likely by way of the recent work done on genericising the Hero Header).

https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/board?repos=430796806

**Comment by charlesons** [comment]
Created a separate ticket for the BDD test for image in the promo banner https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gss-cogs/dd-cms/688
