### ISSUE TITLE
User Research - General CMS Usability

### ISSUE THREAD

**Issue by HarryFergie** [GSS-Cogs/dd-cms#518]
The UX team are going to be trialing a change in the way they work, so that design and dev work can be more closely aligned to user research and that the findings are more usefully documented and shared. Currently, the UR function is validating designs/dev that has been done based on limited information or assumptions and not always directly from research (for various reasons including; a lack of existing UR, approaching deadlines, etc)
 
There is still a need for immediate UR on the CMS project, while we’re in the process of making changes to our way of working. For this reason, for the next phase of research on CMS we will operate 2 parallel pieces of UR;

One of these rounds of research will involve general usability style testing of what has already been developed, to get feedback on what we have so far, so that immediate dev improvements can be made to the live site.

Rough aims/objectives:
- What is working well?
- What challenges are being encountered?
- What do users need to use CMS effectively/what’s missing?
- General improvement opportunities
- Answer any specific questions the devs currently have
 
Methodology: 
- User interviews with Bec, Shannon and Osamede - all of the above
- Diary study - challenges, suggestions for improvement

**Comment by HarryFergie** [comment]
@peterfrenchons - should this be tagged to CC? I think this is more general CMS bits? Sorry I would update the tag myself but I am having issues with ZenHub

**Comment by peterfrenchons** [comment]
@HarryFergie good call

**Comment by HarryFergie** [comment]
Quick update - diary study doc shared with Bec for her to add to as and when required.

Will be catching up with Bec in addition to this for some shadowing/observation shortly.

**Comment by HarryFergie** [comment]
Probably will split this ticket into three: one for usability research with CC CMS users, one for DCMS CMS users and finally one for VAWG CMS users

**Comment by HarryFergie** [comment]
John and I have now caught up with majority (if not all) current CMS users and shared diary study doc. Just awaiting responses from users about when they have availability to do some observations with John and myself. Ticket on hold until we get response back
