### ISSUE TITLE
Cookie consent

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#527]
As per https://design-system.service.gov.uk/components/cookie-banner/ we need a cookie consent banner with details about what cookies may be used.

![image.png](https://images.zenhubusercontent.com/5d933867e92ed00001e35647/f80156f2-a703-450f-b197-dc94de775e43)

**Comment by ajtucker** [comment]
See https://github.com/collective/volto-cookie-banner

**Comment by charlesons** [comment]
Using `volto-cookie-banner` and `collective.volto.cookieconsent` the out of the box capability gives the following results:

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/d98ff43d-987f-469c-aafe-e3e530e6e543)

**Comment by charlesons** [comment]
The implementation of `volto-cookie-banner` is quite basic (offering a simple message and confirmation button by default). To implement more than this would require extending the component. 

The standard GOV.UK cookie consent banner requires more functionality than a simple cookie banner.

An existing [React cookie banner](https://not-gov.uk/components?name=Cookie%20banner) component from NotGovUK looked like a promising alternative but we encountered some issues with SSR in loading the library. 


We we able to amend the razzle config so `@not-govuk/cookie-banner` is no longer handled as an external dependency by expanding the test in line 55 of `razzle.config.js`  as follows:

`      if (/(govuk-react-jsx || @not-govuk\/cookie-banner)/.test(request)) {...
`
A similar SSR issue then arose with the `formidable` library which is a dependency of `@not-govuk/cookie-banner` that we were not able to resolve by extending the externals test:

`      if (/(govuk-react-jsx || @not-govuk\/cookie-banner || formidable)/.test(request)) {...
`

**Comment by charlesons** [comment]
![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/fc3ccedb-8ad3-490c-a292-b4c06b4fd495)

**Comment by charlesons** [comment]
![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/b084b91d-5a1c-4510-ba60-a766a5220123)

**Comment by charlesons** [comment]
When JS is not enabled the main gov.uk site cookies page shows a message advising users to enable javascript. We have replicated the same behaviour.

Screenshot from https://gov.uk/help/cookies

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/95c841c2-0df0-4401-ae52-0cfe1cb9f9bb)
