### ISSUE TITLE
Staging deployment for DCMS and VAWG

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#530]
- [x] Agree on staging domain names, e.g. dcms.ukstats.dev; vawg.ukstats.dev. Note that these may need whitelisting to work on locked-down / constrained networks.
- [x] #557
- [x] #558

Optional:
- [x] Change labelling for "hero" header content block. - implemented by issue #542

**Comment by charlesons** [comment]
Changing of the hero header label will be implemented in issue #542

**Comment by ajtucker** [comment]
Domain name for staging to be vawg.ukstats.dev and dcms.ukstats.dev

**Comment by TahaRana97** [comment]
@anojperera @charlesons any idea about 558?
