### ISSUE TITLE
Making the CCv2 Components dynamic

### ISSUE THREAD

**Issue by nosnickid** [GSS-Cogs/dd-cms#54]
First step to get the most recent articles (actually news items) in date order.

**Comment by TahaRana97** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/GSS-Cogs/dd-cms/54?planning-poker) with ZenHub @ajtucker @cjfairchild @nosnickid @rossbowen

**Comment by nosnickid** [comment]
Create RelatedLinmks dynamic

**Comment by nosnickid** [comment]
Next step is to register a layout_view for the new article content type, using some of the components from my  'static' preview layout views, and make them use the actual article content.

**Comment by nosnickid** [comment]
PR https://github.com/GSS-Cogs/dd-cms/pull/111

**Comment by nosnickid** [comment]
Merged in #111
