### ISSUE TITLE
Resolve issue with internal page links in the Slate Editor

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#553]
Internal links created with the slate editor to figures contained within the same page open up those figures as a separate piece of content rather than link to the instance of the figure within that page.

Behaviour of the internal links should be the same as on the Climate Change 1 site, e.g. on the article The UK Climate is Changing, clicking on the link referencing figure 1 scrolls the reader down to figure 1.

https://climate-change.data.gov.uk/articles/the-uk-climate-is-changing

**Comment by edd-harvey** [comment]
Couldn't find issue - closing until further notice
