### ISSUE TITLE
Give users ability to view the data behind specific charts

### ISSUE THREAD

**Issue by HarryFergie** [GSS-Cogs/dd-cms#555]
As an end user viewing charts, I need to be able to view the data behind this chart, so that I can make use of this data in my own time and way.

**Comment by HarryFergie** [comment]
As an end user viewing charts, I need to be able to view and download the data behind this chart, so that I can make use of this data in my own time and way.

**Comment by HarryFergie** [comment]
User interviews/usability test conducted on this feature W/C 12/09 with multiple users recruited via HotJar. Currently in the process of analysing and writing up the findings from this round of research. Can then:

- Amend current designs where possible and move them to development
- Potentially conduct further research on certain designs if required

**Comment by JohnLewisUR** [comment]
We tested the design for this and it seemed to meet the need of being able to access the data behind the chart. BUT, we need to have a discussion around how this functionality differs from what is being offered by the data explorer/PMD, and whether we actually want users to access/use data from a dashboard, or if we want to direct them to the explorer.
**Recommendation** is that until some of these wider discussions are held, we shouldn't send this for dev, as there may be a better solution if we have a unified service

**Comment by HarryFergie** [comment]
Now closed as turned into a development ticket
