### ISSUE TITLE
Dashboards supernav menu description needs to be parameterised 

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#571]
The text that currently says 'Dashboards about the different indicators of climate change' should be configurable by the user.

As the menu is not a block component then suggest this be implemented as a site property.

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/e989eb9b-cf11-462a-b21a-b5a74a4fd323)

**Comment by ajtucker** [comment]
Reopening as the tests are silently failing :(

We need to update the CCv2 content with the dashboard summary.

**Comment by ajtucker** [comment]
Failing test closed by #587
