### ISSUE TITLE
Make the 'About the portal' menu option in the supernav drop-down menu generic or dynamic

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#574]
The VAWG website design has a page 'About the website' which is currently linked from the supernav menu as 'About the portal'. Naming of this menu option should ideally correspond to the name of the page.

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/47995b2d-0e74-4927-a3d2-8dcb07cee05e)

**Comment by eldeal** [comment]
called 'About' now, done
