### ISSUE TITLE
Whitelist vawg.ukstats.dev

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#580]
Users who have a corporate web filter enforced are unable to use staging/demo sites under `ukstats.dev` unless we whitelist the site/domain, e.g.

![image (4).png](https://images.zenhubusercontent.com/5d933867e92ed00001e35647/820d39b8-f96c-4d29-bc0c-b04fdc8ff33c)

Note that all sites under `ukstats.dev` are currently running behind the same IP address, 35.189.112.127, though in future that will be 34.111.203.231.

**Comment by JasonHowell** [comment]
What is the actual process for white listing this web address? and are we white listing the individual addresses:
vawg.ukstats.dev
or 
<nnn>.ukstats.dev
?

**Comment by TahaRana97** [comment]
waiting for more news after chasing

**Comment by peterfrenchons** [comment]
Done 22/09. ukstats.dev now whitelined
