### ISSUE TITLE
Give users the ability to navigate to page content

### ISSUE THREAD

**Issue by JohnLewisUR** [GSS-Cogs/dd-cms#594]
Giving users the ability to navigate through a long page - design will be to have a table of contents that links users to the appropriate content/section

**Comment by HarryFergie** [comment]
User interviews/usability test conducted on this feature W/C 12/09 with multiple users recruited via HotJar. Currently in the process of analysing and writing up the findings from this round of research. Can then:

- Amend current designs where possible and move them to development
- Potentially conduct further research on certain designs if required

**Comment by JohnLewisUR** [comment]
UR findings - We showed a table of contents at the top of the page, which was usable by all users. The only issues related to the chart titles being long, and/or very similar to each other, making it difficult for users to 'find' the chart they needed. 
I think this is something that can be pushed through for dev, but that we may need to come back to this at a later date to iterate and further improve

The 'sticky' table of contents for the article article pages also tested well, but we shouldn't have different table of contents across the site. But there is scope to do further research/design on the table of contents - specifically with DCMS as they have a large report that will need a table of contents.

**Comment by JohnLewisUR** [comment]
We recognise that this table of contents may not be suitable for all content types - we have only tested this with the content on the climate change portal, so will need to be reviewed as and when we start dealing with other content (DCMS)

**Comment by gareth-lewis** [comment]
![image.png](https://images.zenhubusercontent.com/62bc138cfba24f8002b96a0a/3eb02a9e-6ca5-440a-95b3-8b7a153499d7)

![image.png](https://images.zenhubusercontent.com/62bc138cfba24f8002b96a0a/e8788b59-985c-49e7-b8b8-4ffedf207c63)

**Comment by HarryFergie** [comment]
Closed as development ticket now created
