### ISSUE TITLE
Ability for users to navigate from within a page back to the top

### ISSUE THREAD

**Issue by JohnLewisUR** [GSS-Cogs/dd-cms#596]
When users have navigated to content on a page, they need to be able to get back to the top of the page without scrolling.
Design will be having a 'back to top' or 'back to table of content button'

**Comment by HarryFergie** [comment]
User interviews/usability test conducted on this feature W/C 12/09 with multiple users recruited via HotJar. Currently in the process of analysing and writing up the findings from this round of research. Can then:

- Amend current designs where possible and move them to development
- Potentially conduct further research on certain designs if required

**Comment by gareth-lewis** [comment]
![image.png](https://images.zenhubusercontent.com/62bc138cfba24f8002b96a0a/8befafa8-d68b-409f-b326-99647126eb77)

**Comment by HarryFergie** [comment]
Closed as development ticket now created
