### ISSUE TITLE
Figures with multiple charts don't seem to render correctly after edits to a subset of the charts in that figure

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#607]
The bug isn't fully defined yet and needs further exploration to understand it.

An example figure that had the issue was Figure 3 in the article https://staging.climate-change.data.gov.uk/articles/emissions-embedded-in-trade-and-impacts-on-climate-change

The charts appeared as shown below. Refreshing the article and opening the figure and re-saving did not resolve the issue.

![image (5).png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/87d58dd7-ba15-4cb2-948e-084a804d4721)

In the example above we were able to resolve the issue by updating a property for all charts in the figure in the same save cycle (we set the top margin to 1px).

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/16b95a6a-306d-4835-9cf4-acd0e5082f69)

**Comment by edd-harvey** [comment]
We don't think this is an issue anymore - closing ticket.
