### ISSUE TITLE
site.webmanifest missing

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#618]
We've noted in the dev console that `/site.webmanifest` is missing. The resource is referenced in the `<head>` of every page as as `<link>` by the default Volto frontend.

According to the [Bootrapping a Volto Project](https://training.plone.org/5/volto/bootstrap.html) instructions, it should have been created along with some other static files in `public/site.webmanifest`.

**Comment by ajtucker** [comment]
Looking at the autogenerated `public/site.webmanifest`,

```json
{
    "name": "",
    "short_name": "",
    "icons": [
        {
            "src": "/android-chrome-192x192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "/android-chrome-512x512.png",
            "sizes": "512x512",
            "type": "image/png"
        }
    ],
    "theme_color": "#ffffff",
    "background_color": "#ffffff",
    "display": "standalone"
}
```

it obviously needs to be customised per site. The intention of this file is to enable Progressive Web Apps that can be installed on a user's local device.

We're not offering this feature at the moment, so we could:
* customize [src/helpers/Html/Html.jsx](https://github.com/plone/volto/blob/master/src/helpers/Html/Html.jsx#L133) to remove the link.
* use the above minimal template & if we need to customize it later, maybe use some middleware route.

The only issue we're seeing is in the dev console where HTTP requests are being made to a non-existent resource and so returning 404 not found. However, when we use HTTP Basic Auth to keep a site private, this can confound the issue of authorization.

**Comment by edd-harvey** [comment]
Looked at this in refinement and was unsure - @eldeal can you have a look and see if it's still needed
