### ISSUE TITLE
Data / Visualisation Download Capability

### ISSUE THREAD

**Issue by edd-harvey** [GSS-Cogs/dd-cms#637]
- [x] Figure image download (as PNG) including all of the supporting text (minus the UI features incorporated into the figure)
- [x] Chart data download as CSV. The included columns will be the same as the series shown in the chart.

**Button placement as per Figma design shown below:**

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/67d4cd23-1150-4877-af86-075d56c90671)

### **Problem**
Users want to download visualisations and the associated data within dashboards in the climate change portal. Users currently have to screen shot charts and graphs and navigate to the datasets tab to view the data.

### **Appetite**
We want to ship a data and viz download feature within two sprints (6 weeks) that alleviates the need to screen shot or navigate elsewhere for the data.

### **Solution**
Beneath each visualisation there is a 'Download' section with download links for the visulaisation in the following formats; JPEG, PNG, SVG and download links for the data in CSV or Excel format. See emissions dashboard within the [design template](https://www.figma.com/file/n61a8x7kKnkriF7b9XAADl/Climate-Change?node-id=1374%3A11462) for Gareth's mock up.

### **Rabbit Hole**

1.  What happens when we click the link? To avoid going down any rabbit holes, we just want the visualisation or dataset to begin downloading to the download folder within the browser.
2. What data are we downloading? for now we are downloading the data that sits behind the visualisation that is returned in the SPARQL query

### **User Story**

**As a** user of the climate change portal
**I want** to be able to download visualisations and the associated data from within an article
**So that** I can use them for my own purposes

**Comment by charlesons** [comment]
For multi-chart figures like this one the design doesn't quite fit as presumably each chart would have a download button whereas there would be a single download button for the figure as a whole.

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/d9706b74-2e4d-45dd-9f16-af313a779404)

**Comment by charlesons** [comment]
The Download Data aspect is implemented in https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gss-cogs/chart-builder/170
