### ISSUE TITLE
Example RBAC workflow

### ISSUE THREAD

**Issue by rossbowen** [GSS-Cogs/dd-cms#64]
Some example of some trivial workflow, e.g.

`Ross` is a statistician who wants to publish an article.
`Alex` must approve the publication prior to it being published.
Once approved, `Ross` may then publish the article.

Done: worked example / demo

**Comment by ajtucker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/GSS-Cogs/dd-cms/64?planning-poker) with ZenHub @charlesons @cjfairchild @osamede20
