### ISSUE TITLE
Toggle between charts and tabular view of data

### ISSUE THREAD

**Issue by TahaRana97** [GSS-Cogs/dd-cms#658]
- [x] Chart data will show in a table as per Figma design shown below
- [x] Data shown are the selected series in Chart Builder
- [x] Will have pagination
- [x] Will have horizontal scrolling

- [x] Implementation will be a feature in Chart Builder (and not the CMS)
- [x] The content creator may selective show: Tabular data only (with no tab options showing above the table) or Chart plus tabular data view (with tabs to navigate between them)
- [x] Tabular data will show for maps indicating the location and value for each observation
- [x] Cells for sparse values will be left empty

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/6c078f68-5cc8-4158-a885-ec5308760e6b)

**Comment by eldeal** [comment]
Some of the value of this comes as it's more compatible for screen readers, so it's important to me we consider what it would sound like to a screen reader when deciding on the tidy data vs human-friendliness of the table format.

**Comment by charlesons** [comment]
Spec agreed and approved with @gareth-lewis in design meeting 07/11/2022

**Comment by canwaf** [comment]
> We see this as a Chart Builder feature (as opposed to a CMS feature) and propose the coding be done within Chart Builder. The table (as currently specified) will be dependent upon and display the series data derived from chart builder's internal logic that pivots from TidyData to columnar data. A bonus of this approach is that the tabular view of data would be available to any other applications that make use of the standalone Chart Builder. Are we happy with this approach?

I am happy with this approach.

> Will there be an option for the content creator to selectively show only the chart view, data view or both? Or will the tabs at the top always show?

I think the visualiser should be able to show table only, but if they select a visualisation it should be visualisation and tabs. This helps with accessibility.

> Would the tabular view of data be available for maps? (showing a simple table of region label and value)

I think this is a requirement, yes.

> Where there are sparse data should the empty observations be indicated with a dash, a zero or something else?

We need to support observation status values in this case. Not applicable, not available, suppressed are all different reasons. These values can be brought in as part of the SPARQL query, and should be filled in. Zeros cannot be used, but blanks can be left for now.

**Comment by charlesons** [comment]
@canwaf, thanks for the clarifications. Spec revised accordingly.
