### ISSUE TITLE
Disable user self enrolment on vawg and climate change beta sites

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#664]

**Comment by charlesons** [comment]
Test carried out in the staging environment of disabling self enrolment with the following results:

Turned off the `Enable self-registration` setting in the security tab of the Plone control panel - this did not prevent self registration using OAuth. This suggests that the enrolment settings for OAuth may be managed separately.

**Comment by charlesons** [comment]
Further exploration of the issue hasn't identified a straightforward way to prevent self registration when users log in using OAuth.

As this forum post highlights, with OAuth there isn't a way to whitelist certain 'known' users as they login because the authentication is done by a third party (who's authentication logic would have no awareness of existing user list).  

https://stackoverflow.com/questions/47902578/google-oauth-login-how-to-allow-only-whitelisted-emails-to-log-into-my-app

This also raises questions around the UX of potentially allowing users to Log In even when they don't have an account.

Suggest that the way forward is to redefine the requirements. Some options might include:

1) Continue as is where users who login using OAuth are self registered (by way of logging in) but initially have no roles assigned
2) Attempt to limit the scope of OAuth users to specific domains
3) Use the Plone-Volto inbuilt user management

**Comment by charlesons** [comment]
Path forward to be discussed at Infra meeting on 5/10/2022. Moving the ticket to sprint backlog for now.

**Comment by charlesons** [comment]
Posted a question in the Plone Discord chat and the folks there recommended looking into creating a whitelisting of users in our OAuth provider (GCP). By having an upstream whitelisting this would effectively prevent self-registration within Plone-Volto from ever happening.

**Comment by eldeal** [comment]
For the purposes of hard launch, happy to just ensure there are no permissions given on self-enrolment account creation

**Comment by charlesons** [comment]
Consensus amongst the team is that a pragmatic solution in the short term is hide the login link. Ticket created for this:

https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gss-cogs/dd-cms/718

**Comment by JasonHowell** [comment]
Dependant on other architecture discussions/decisions.

**Comment by JasonHowell** [comment]
Still outstanding.  Low priority.
