### ISSUE TITLE
Create a control panel section for site wide properties

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#667]
Create a Volto control panel section or extend the existing Site section so users can set site-wide properties for the CMS.

Site-wide properties to include:

- Site title
- Phase banner show/hide, phase and feedback link properties
- HotJar ID and version parameters
- Google analytics ID

Adjust the implementations of the above properties to pick up the respective properties from the site properties rather than the current sources (Hero header and environment variables).

**Comment by charlesons** [comment]
Some useful docs here https://training.plone.org/5/mastering-plone/registry.html

**Comment by anojperera** [comment]
On Macbook's with arm processors, run below command to download the docker image first before running `./bootsrap.sh`

`docker --platform linux/x86_64 create plone:5.2.7`

This will download the correct docker image

**Comment by anojperera** [comment]
![Screenshot 2022-11-01 at 11.46.00.png](https://images.zenhubusercontent.com/619f67e36a20872245102c1c/2cae3865-bff9-49dc-ae96-20805f777824)

![Screenshot 2022-11-01 at 11.46.31.png](https://images.zenhubusercontent.com/619f67e36a20872245102c1c/78a7aab6-f151-4d97-a5b2-0e0ba5ffeddb)
