### ISSUE TITLE
Create a CMS cluster for development testing - sandbox.ukstats.dev

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#668]

**Comment by eldeal** [comment]
Mikes progress so far: the cluster is up but automating the basic auth is giving issues so we cant get in yet.

**Comment by TahaRana97** [comment]
@mikeAdamss can you confirm if this is a priority task based on the current sprint objectives? 
https://docs.google.com/document/d/1rmWaRRzFtz5U2wBjGkYoTJxxxJQbzvxouN5SIOodEwM/edit#

**Comment by mikeAdamss** [comment]
fair question - its more facilitating. I'm better placed to pick this up than the others devs (this stuff is very niche) and it'll remove some pain points and help the sprint team progress on things like the performance improvements.

best to think of me more as bonus resource for the time being, if I wasn't picking this up, I'd be picking up something non CMS related :smile:

**Comment by TahaRana97** [comment]
@mikeAdamss in that case i will leave it in development as a nice to have - but pls do update it with the latest commentary on progress so we can manage the ticket accordingly

**Comment by mikeAdamss** [comment]
## What this is

Create a PR into the https://github.com/GSS-Cogs/idpd-platform repo with a fully IAC (infrastructure as code) solution to creating and managing a environment worth of infrastructure.

Please note: an "environment" for now roughly equates to a kubernetes cluster but in time that will expand to include other web based resources our service offerings depend on.

IAC is a pre-requiste to complex infrastucture orchestration, acceptance testing and secure networking. This "sandbox" environment is being created as a means to iron out approach and areas of complexity with an eye on (eventually) using the same tooling is to provision production and staging environments.

## Acceptance Criteria

- [ ] All infrastructure defined as code that can be applied in a repeatable idempotent way to create an environments worth of infrastructure.
- [ ] Creating an environment should be approximately **two commands** (one for provisioning, one for orchestration).
- [ ] A working sandbox environment.
- [ ] All hard coded assumptions to be pulled out into variables so the same IAC resource can be applied to any environment.
- [ ] Documentation so developers can make changes to infrastructure in a clean and repeatable way.
- [ ] Where possible, add any self repair / config enforcement logic, in so far as we can without going off point too much. 

**Note** - this is a **transcription of existing CMS infrastructure only**, any outstanding concerns about security, architecture or approach to be addressed as separate issues, i.e this is "create a magic button to wrap what we currently have" not "what should we have" or "what should the button do".

**Comment by mikeAdamss** [comment]
progress:

- IAC exists
- sandbox environment is spun up.

TODO:
Much documentation to do, tidying up needed to make it a viable resource for other less ops focussed developers.
Database is currently not bouncing back on restarts, need to fix this.
Need a dynamic way for developers to choose the branch to deploy into sandbox for working with long running feature branches.
Service restarts are resulting in minor downtime windows, this may be an existing k8s issue rather than just this card, but will look at it.
(good to have) - mechanism to sync data from production so developers don't need to do it manually.

**Comment by mikeAdamss** [comment]
@TahaRana97 added some content. In regards to estimate I would put this as a 13 rather than a 3 (I think I saw a 3 earlier).

**Comment by mikeAdamss** [comment]
done
