### ISSUE TITLE
Investigate publishing workflow options in Plone

### ISSUE THREAD

**Issue by eldeal** [GSS-Cogs/dd-cms#686]
In order to resolve pain points around getting new sites set up, we need to advance our service offering to allow 2 new behaviours:

- Unpublished (draft) data from Drafter must be available to unpublished content pages in the CMS
- A user should be able to perform a single action to publish related pages in the CMS and related draftsets in Drafter.

We need to investigate a few areas to deeper understand the technical options for managing publishing of content in the CMS to better inform conversations for both new behaviours.

Investigations needed:
- [ ] BA requirements need clarifying
- [ ] Could we call the Plone API to publish multiple pages? Is there anyway to identify a group/collection of pages that need to be published?
- [ ] What would be required to allow CMS pages to call unpublished draftsets in Drafter?

**Comment by anojperera** [comment]
We had an initial conversation with Ric from SWIRL and we agreed to have an intermediary service which is aware of PMDs workflow and CMS. This will allow a user to use draft data and publish it via CMS and vice versa
