### ISSUE TITLE
Error when saving pages that have language property set

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#691]
The following error is encountered when the language property is set on a page but the langauge settings are not configured for the site.

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/24ce21ff-4e2f-40de-9e6b-10b2e2360d98)

The page property that causes the error state (on save) is:

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/33f35086-2b38-4b99-ae67-b2acb5322919)

**Comment by charlesons** [comment]
The solution to the issue is to:
1. In [site root]/controlpanel/addons Ensure the `Multilingual Add On` is installed 
2. In [site root]/controlpanel/language set the `Site Language` and `Available Languages` as required for the site. e.g.:

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/84f8e4b0-371d-4c65-af7e-9039077c5e7b)

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/d11aecc6-c9cf-4b22-ae63-1d3a98017f76)

**Comment by charlesons** [comment]
Suggest that the above configuration are automated for new site deployments.

**Comment by anojperera** [comment]
We have tried to resolve this by setting the language to the en.json. However this prohibited us from saving. Therefore we reverted back to en_gb.json. To be addressed later.

**Comment by charlesons** [comment]
Created issue [#716](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gss-cogs/dd-cms/716) for future work on multilingual support.
