### ISSUE TITLE
Security issue with Sandbox and Staging VAWG sites

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#697]

**Comment by charlesons** [comment]
![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/ea7eaff4-77c5-41c9-8856-25ccf7eb1af1)

**Comment by mikeAdamss** [comment]
fixed this in passing, was googles fault, requested a re-indexing and it went away.
