### ISSUE TITLE
Fix (if possible) overlapping / too short text widths of Volto block properties

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#700]
The text for block properties in the side panel isn't very easy to read (the properties overlap each other), e.g. when setting the properties for tables. Although this styling is set by Volto we may be able to tweak it ourselves to fix the issue. Doing so should benefit users across the range of block content available in the CMS. 

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/aabadc29-b590-46cc-aa97-154bbdf26481)

**Comment by StRhys** [comment]
![image.png](https://images.zenhubusercontent.com/62f20b9a8dde10123518450a/c929ede0-4a24-4f3d-a8c2-26f09e723362)

**Comment by StRhys** [comment]
Copied over the `CheckboxWidget` folder from omelette and used that in the same way we would shadow a `view`, changed the css to extend width to full.
Also copied over the `Widgets` config, and changed the import for `CheckboxWidget` from @plone to our shadowed version within our files
