### ISSUE TITLE
Decommission CC Beta and CC v1

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#719]
- [x] Turn off CCv1 in CloudRun - **02/11/2022**
- [x] Decommission beta.climate-change.data.gov.uk - **02/11/2022**
  - [x] Update CNAME records for staging to not reference beta
  - [x] Make sure we can still route to the staging env
  - [x] Remove beta config from the ingress and NGINX

**Comment by mikeAdamss** [comment]
updating with a few additional tasks as there's quite a lot under the surface here

- [ ] remove climate change v1 release cloud run
- [ ] remove/disable build job for climate change v1 release cloud run
- [ ] remove DNS entry for v1 staging release 
- [ ] remove climate change v1 beta cloud run
- [ ] remove/disable build job for climate change v1 beta cloud run
- [ ] remove DNS entry for v1 beta release
- [ ] remove static IP addresses for both
- [ ] remove serverless load balancer for both
- [ ] contact swirrl to update any lingering CNAME records.

**Comment by mikeAdamss** [comment]
As a precaution against jumping the gun am going to disable but not delete the build triggers (as long as they exist we can "put it all back" relatively easily.
