### ISSUE TITLE
Site search - return only pages

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#725]

**Comment by StRhys** [comment]
Site owners are able to define the types that they want searched and returned.
This can be accessed via site setup->search
![image.png](https://images.zenhubusercontent.com/62f20b9a8dde10123518450a/999bf167-60cc-4844-8f92-5e3c88e4072e)

**Comment by StRhys** [comment]
Need to look into if search site settings can be setup as defaults on site spin up

**Comment by charlesons** [comment]
Configured the site search to only return pages but the configuration seems not to take effect.

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/ef6e36ee-6e29-4e72-b24c-f746809f403b)

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/67de5342-d0cb-468f-96ba-29174e615afa)

**Comment by StRhys** [comment]
![image.png](https://images.zenhubusercontent.com/62f20b9a8dde10123518450a/1588a071-3da3-4305-ab2d-c9efcf55411d)
Contradictory to what the text says in search settings, it is the excluded types that are searched.
So leaving out the type 'page' means only pages are returned, which are called @type 'document' in this case.
![image.png](https://images.zenhubusercontent.com/62f20b9a8dde10123518450a/7a0a12db-3c81-4e21-b0e9-59b91d9d7658)
![image.png](https://images.zenhubusercontent.com/62f20b9a8dde10123518450a/583c6265-abab-4f59-95c4-c2b8f4ada1d2)

**Comment by charlesons** [comment]
Reviewed this again in light of @StRhys findings and confirm that by specifying content types to exclude from the search we can get the intended results (i.e. only pages).

**Comment by charlesons** [comment]
Pending task is to apply this config in Production

**Comment by charlesons** [comment]
Changes applied and have taken effect on the Climate Change site 

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/5f7d609f-4303-42dd-b7d9-41d9870f7b62)
