### ISSUE TITLE
Create release v1.0.0 of Chart Builder and reference it from dd-cms

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#733]

**Comment by charlesons** [comment]
Created release v1.0.0 of Chart Builder. 

Release notes here: https://github.com/GSS-Cogs/chart-builder/releases/tag/v1.0.0

**Comment by mikeAdamss** [comment]
had a quick look at this while waiting on something for a different card. Charles has written this but currently this is failing to build on GCP with a timeout.

my understanding (to be taken with a pinch of salt) is:

- there's 2 ways to yarn build, `dev` and `prod`
- dev works, which I suspect is why it got this far
- prod does not work
- prod uses a javascript tool named "babel" that as far as I can tell compresses the javascript as part of building a production version of an app
- babel has a default maximum file size it will compress of 500kb which (I think, from the gcp logs) is timing out as some of the new plotly related javascript files exceed that. 
- you are able to change this babel default, but the recommended use of a "babelrc" file does not work (or I was doing something wrong).

TODO - somehow up the filesize that babel will compress in order for this branch to build with yarn:prod.

I'd guess you can build like that locally but I honestly don't know

**Comment by StRhys** [comment]
This has been updated to include v1.1.0
