### ISSUE TITLE
Design considerations on data download, tabular view of data and figure download for figures with multiple charts

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#734]
During implementation of issues: 

#658  (which adds the capability to for readers to see a tabular view of data instead of the chart/map view)

and

#637  which offers the user the ability to download of the chart data/image of the figure)

a design question has arisen around how these capabilities should function when there are figures containing multiple charts.

Some specific questions are:

1. Should the tabular view of data show when there are two charts shown side by side in a chart comparative view? In this scenario the table columns would have limited screen width in which to display.

2. Should the download figure button be available also at the chart level or only for the figure as a whole?

3. A broader question on what is the appropriate level of constraint to apply to content creators in creating figures with more than one chart? For example should they be limited to max 2 charts per figure? 

4. Could we make use of small multiples charts for visualising comparative charts? and then allow users to download the data behind all of the shown multiples.

An example of a figure that prompted this line of thought is Figure 3 in the article below:

https://climate-change.data.gov.uk/articles/emissions-embedded-in-trade-and-impacts-on-climate-change

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/dccdca61-7671-43fb-acb6-e9aae34afaf0)

Additional point following further discussion: 

There is still an unanswered question as to whether a user would need access to solely the visualisation itself when they download it - or also the associated content that sits alongside it ie. the description, the source etc.

For the purposes of our first release, we have gone with the assumption that the user requires both the visualisation and the content - and this has been built in ticket 637. For a later iteration, we may want to validate with users whether this is actually the case and then iterate as required.

**Comment by JohnLewisUR** [comment]
Decisions from UX/PO catch up:
2 charts per figure for a 'comparative chart' component (ideally side by side)
1 download button per figure
1 tab per figure (for data view)

**Comment by HarryFergie** [comment]
Design work now complete. Now sitting with the climate change team to implement changes.

**Comment by edd-harvey** [comment]
CC team have implemented the required changes and this no longer blocks the release of the data / vis and download features - moving to closed
