### ISSUE TITLE
Technical report on performance improvements in the short and medium term

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#753]

**Comment by charlesons** [comment]
Report (presently draft) is stored in a page of the CMS wiki https://github.com/GSS-Cogs/dd-cms/wiki/Site-performance-targets-and-optimisation

**Comment by eldeal** [comment]
@StRhys next time you're between tickets can you have another look at the linked wiki page, particularly in the "We identified a list of possible actions to improve performance:" section. I've tried adding links to cards we raised to do this work, but I wasn't sure whether I got them all or if there's any other tickets you can link to in there?

Basically just thought it'd be helpful going forward to be able to click through and see whether we've actually shipped each potential improvement or not / the status of the relevant tickets :)
