### ISSUE TITLE
Make the endpoint for site wide properties public

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#755]

**Comment by eldeal** [comment]
If one of these properties is the Hotjar ID then this is blocking getting IAC into prod. My understanding is this ticket means there is an endpoint but it needs to be made available for GET requests on public page loads to provide these variables as needed.

**Comment by eldeal** [comment]
@edd-harvey it's quite important we solve this within the next sprint to unblock @mikeAdamss or so he knows he needs to find an alternate solution

**Comment by eldeal** [comment]
Potential alternate approach to use middleware instead of exposing the endpoint https://github.com/GSS-Cogs/dd-cms/compare/main...one-volto

**Comment by eldeal** [comment]
We want to get to a point where we have:
http://localhost:3000/++api++/@cmsconf-site_title
http://localhost:3000/++api++/@cmsconf-site_banner
http://localhost:3000/++api++/@cmsconf-GA_ID
http://localhost:3000/++api++/@cmsconf-Hotjar_ID

**Comment by eldeal** [comment]
GA and Hotjar IDs are just strings
