### ISSUE TITLE
ToC bug on 'The UK’s climate is changing'.

### ISSUE THREAD

**Issue by StRhys** [GSS-Cogs/dd-cms#756]
When on The UK’s climate is changing article, if 'Rainfall' is clicked on the ToC an error is thrown.

**Comment by StRhys** [comment]
Put a conditional statement in `scrollTo` if it's unable to find element by id.
The actual issues seems to be deeper though.

**Comment by StRhys** [comment]
![image.png](https://images.zenhubusercontent.com/62f20b9a8dde10123518450a/fea76bf9-13eb-45b4-834e-a2bb2c4fe674)
![image.png](https://images.zenhubusercontent.com/62f20b9a8dde10123518450a/994576b3-92d8-4e21-80a4-5b90faadd4c3)
Issue seams to be resolved by placing an empty <p> block above the 'Rainfall' heading.
When placing 'Rainfall' above 'Temperature' the issue stopped.
When creating another header above 'Rainfall' the issue would effect the new header.
Still unsure about the deeper cause of thee issue.

**Comment by eldeal** [comment]
Is there a PR for this or was this just a content change?
