### ISSUE TITLE
Design options for when the user wishes to have more (or less) than 6 dashboard tiles on the homescreen

### ISSUE THREAD

**Issue by HarryFergie** [GSS-Cogs/dd-cms#761]
We have had some feedback from the VAWG team that they would like to add more dashboard tiles to the homescreen as they have more than 6 themes under the VAWG umbrella.

Gareth to consider design options for when 6 tiles is not enough (or too many)

**Comment by JohnLewisUR** [comment]
Potential plan (to be reviewed Tues 24th):
UX team to have a design session (crazy 8s?) to generate some ideas for topic page templates
Design to generate low fidelity wireframes which can be taken our by UR to get feedback from publishers.
Engage directly with VAWG team to understand what content they have and want to publish - so Design can get a better picture of what options we need to provide to cater to their needs.

**Comment by gareth-lewis** [comment]
![image.png](https://images.zenhubusercontent.com/62bc138cfba24f8002b96a0a/7a8333bd-5496-40b6-8f0a-27afb0b15ace)

![image.png](https://images.zenhubusercontent.com/62bc138cfba24f8002b96a0a/6318617c-9110-41ce-b929-0278590ecc23)

![image.png](https://images.zenhubusercontent.com/62bc138cfba24f8002b96a0a/ddf4e4d5-2f50-4b8d-8006-136314f195d3)

![image.png](https://images.zenhubusercontent.com/62bc138cfba24f8002b96a0a/45aa3911-3a92-408f-8925-f2b137284dcf)

![image.png](https://images.zenhubusercontent.com/62bc138cfba24f8002b96a0a/011edc01-44a7-4b5e-bcd3-277309e344bd)

![image.png](https://images.zenhubusercontent.com/62bc138cfba24f8002b96a0a/d6696141-8d9d-479d-ac9f-b6fb73090248)

![image.png](https://images.zenhubusercontent.com/62bc138cfba24f8002b96a0a/11a0efb5-7e53-4e97-b755-566a4f51759b)

![image.png](https://images.zenhubusercontent.com/62bc138cfba24f8002b96a0a/a7b26060-7d52-420a-babd-36f6a696ee0a)

![image.png](https://images.zenhubusercontent.com/62bc138cfba24f8002b96a0a/ff8c406b-2280-4ccb-b993-426997219562)

![image.png](https://images.zenhubusercontent.com/62bc138cfba24f8002b96a0a/08f32063-a02d-4faf-a05e-19a573e5460f)

![image.png](https://images.zenhubusercontent.com/62bc138cfba24f8002b96a0a/d7363488-f874-46cb-914d-67b5b45a18ac)

![image.png](https://images.zenhubusercontent.com/62bc138cfba24f8002b96a0a/350431fa-9add-4864-a730-32a0c5a582a3)

**Comment by JohnLewisUR** [comment]
Something else to consider for the longer term is that it likely won't be just be dashboard tiles that teams want on their topic/home pages - they might have other pages or content that they want to 'promote' in some way. Not really something we need to worry about yet, but we'll need to think of moving forward, particularly for DCMS who have just 1 annual output

**Comment by HarryFergie** [comment]
UCD met to discuss this ticket and to agree an approach going forwards. Decision made to move this ticket back in the backlog at this time, as it makes more sense to address this need when we consider topic pages as a whole.

The feeling from UCD is that 'topic pages' feels like more of a Data.Gov feature that we would pick up when we progress with Data.Gov. We could then explore in greater depth the sort of things publishers want to display on a topic page and then the best way to present this to consumers. 

Some specific questions we still have are:

- What is the key content that should be presented to users on a topic page?
- What are the main types of content that publishers wish to publish?
- What if a specific publisher did not wish to publish articles?
- What if a specific publisher did not wish to publish dashboards?
- What if a specific publisher only wanted to publish data without any other associated content?
- How do we cater to all of the above needs?
