### ISSUE TITLE
Support the need for a sandpit environment 

### ISSUE THREAD

**Issue by HarryFergie** [GSS-Cogs/dd-cms#764]
**‘As a publisher, I need a separate ‘safe place’ within the CMS to work from, so that I can test out new features as well as preview potential publications without risking affecting my live site’**
****

We’ve had some feedback from the VAWG team that they have a need for a separate ‘sandpit’ environment within the CMS. The idea being that this space could be used to ‘play around with’ new features within the CMS, as well as being able to preview potential publications before they go live. This would reduce the risk of updates being made to the live site unintentionally.

For us, giving users the opportunity to test out new features in a safe environment would also be a good way to get feedback to drive iterations. It would also allow us to conduct direct user research on the CMS itself and features.

We have received similar feedback when holding user interviews with analysts and publishers across government, who have advised on limitations using Whitehall Publisher. Some examples of this below:

- Whitehall publisher doesn't currently allow users to preview publications with content that hasn't already been published due to security constraints.

- Currently have to manually share draft publications rather than being able to do so in Whitehall publisher. Often this is done in word docs.

Considering the above feedback, I have added this ticket for us to explore opportunities to support this new environment to address these highlighted needs, as well as the need to preview and share publications with the wider team before publication.

**Comment by edd-harvey** [comment]
Had follow up session with Dani from crime team and no longer feel that this is a requirement. We're exploring working copy as well which covers the needs of the user. Closing ticket.
