### ISSUE TITLE
Error on refreshing a figure block in the browser.

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#766]
The following error is raised when refreshing a figure block (as a standalone item of content). 

The error doesn't occur with figure blocks embedded in pages which are seen by the reader viewers of the site.

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/186d6fa2-37bd-4e76-a249-8eb0b8c80688)

**Comment by edd-harvey** [comment]
Uncertainty around frequency of bug
