### ISSUE TITLE
Developing in the Public Web

### ISSUE THREAD

**Issue by JasonHowell** [GSS-Cogs/dd-cms#77]
If you are using Climate Change Portal as a basis to develop the CMS ability in the public web then there has to be consideration on the political impact this could have on ONS from the Climate Change Steering board and any future work. 

In my opinion anything with Climate Change Portal should either be done behind a username/password or clearly stated on the public pages this is experimental development work and we inform the Climate Change Team on what we are doing.

**Comment by JasonHowell** [comment]
Comments from Rob T on slack:
Throwing my hat into the ring on this, at the moment, someone stumbling onto this may mistake it for something official.  The web address it is on means it is less likely, and I hope/presume we have teh tags on to stop search engines discovering it, but as this is a prototype (not a release candidate yet) it should be clearly badged Alpha.
I agree with Jason as well though, this should have a password on it to reduce the risks.

https://onswebsite.slack.com/archives/C02NKAKD484/p1644308346455859

**Comment by ajtucker** [comment]
Note that this discussion and all the source code here is, rightly, open for anyone to see.
