### ISSUE TITLE
Data markers in UI

### ISSUE THREAD

**Issue by JohnLewisUR** [GSS-Cogs/dd-cms#779]
Get more information about what our approach/solution is to displaying nil values/sparsity/disclosive data, etc in the UI

**Comment by JohnLewisUR** [comment]
Going to speak to Darren about what we previously agreed with Swirrl about this. It's been mentioned we have previous UR, but this was very limited and I can no longer find this research (possibly not ever stored on Google Drive)

**Comment by JohnLewisUR** [comment]
Have spoken to Swirrl (Ric) - they are already using data markers as attributes in cubes, but it seems like there needs to be a discussion about how these are represented in the data model and in the UI, as there are some unsolved issues around the missing/suppressed values in the cube model.
Also potentially "Part of the issue is that the W3C cube model says that observations need to have a (numeric) value"
Not sure if this si something for UR yet

**Comment by JohnLewisUR** [comment]
Report written by Robin on Data Markers - https://github.com/Swirrl/cogs-issues/blob/master/modelling/data-markers.md

**Comment by edd-harvey** [comment]
What do we want to do with this ticket @JohnLewisUR ? Move to close?

**Comment by JohnLewisUR** [comment]
Yeah, there's nothing more for UR or Dev to do with this. I feel like it does need to be followed up with someone on the data side though (not sure who, maybe Andrew or Martyn?), so that we can work out what needs to happen - it's all a bit above my head

**Comment by JasonHowell** [comment]
What is the standard to follow for this?  Data Manager's to steer.
