### ISSUE TITLE
'About the portal' content tweak

### ISSUE THREAD

**Issue by HarryFergie** [GSS-Cogs/dd-cms#781]
Some feedback from the VAWG team to say that they feel there is some confusion using the terminology 'portal' on their site, as they often refer to it as a dashboard (rightly or wrongly). Could we remove this confusion by updating it to 'About' rather than 'About the portal'

**Comment by charlesons** [comment]
This issue is based on feedback from the VAWG team, however the current 'About the portal' text was specified by the Climate Change team originally. Do we have their agreement for this change?

Suggest @HarryFergie confirm the change is acceptable to all stakeholders.

**Comment by HarryFergie** [comment]
Hey @charlesons, do we have to change both? Ie. if CC are happy with the terminology 'portal', could we leave theirs as is? 

I think longer term we'd need to agree a consistent approach to it, especially when we have one single space where all this lives, but for now it might be less of an issue? @edd-harvey any thoughts?

**Comment by HarryFergie** [comment]
Sorry also I wasn't expecting this one to be picked up yet so apologies for not doing more digging ahead of time.

**Comment by edd-harvey** [comment]
Would be good to change the VAWG text separately if possible to keep climate as is.

**Comment by StRhys** [comment]
The change would have to be across all sites, unless we parameterise it and let them set the text manually?
