### ISSUE TITLE
Improve source link next to charts

### ISSUE THREAD

**Issue by JohnLewisUR** [GSS-Cogs/dd-cms#789]
Had feedback that it isn't obvious that the source link will take you to PMD/the data. This is more relevant now that we're adding the download data button, as it could limit the users who want to get to the full dataset on PMD.

'As a consumer I need a clearly signposted journey to the complete dataset behind a chart, so that I can access the data and do my own analysis

Potential solution - amend text to say something like 'See full/source data' and add additional text for data source as part of the chart/figure.

**Comment by eldeal** [comment]
Would including the dataset title in the link rather than or in addition to the owner be helpful?

**Comment by gareth-lewis** [comment]
![image.png](https://images.zenhubusercontent.com/62bc138cfba24f8002b96a0a/ec5c1819-4bb2-4b83-a539-c85cbe374ff8)

**Comment by HarryFergie** [comment]
Get some feedback from Helen whether this meets her initial expectation

**Comment by StRhys** [comment]
https://github.com/GSS-Cogs/chart-builder/pull/185
