### ISSUE TITLE
Finding help page appears in dashboards section/dropdown

### ISSUE THREAD

**Issue by JohnLewisUR** [GSS-Cogs/dd-cms#812]
The 'Finding Help' page currently appears within the dashboard dropdown, but this isn't a dashboard page. We need somewhere for this content/page to be and for the page to be signposted and navigated to for users.

VAWG have suggested having it as another option in the GOV.UK black heading alongside dashboards and articles?

User story:
As a publisher I need the ability to create content/pages that don't sit within the dashboard hierarchy/menu, so they appear as standalone navigation menu options

**Comment by edd-harvey** [comment]
We need to test how the nav bar works and how it picks up content within the site structure

**Comment by eldeal** [comment]
I've tested this and by using the 'Exclude from Navigation' option on a page it is removed from the Nav Bar but still returned in search results. This should be fine for users to work with immediately.

![Test 'Exclude from Navigation'](https://user-images.githubusercontent.com/7114478/217843556-0a6588a2-a216-495a-9ee2-e9c2c8a32554.gif)
