### ISSUE TITLE
Dashboard tiles show data to 2 decimal places for sparklines

### ISSUE THREAD

**Issue by JohnLewisUR** [GSS-Cogs/dd-cms#816]
Sparkline dashboard tiles show data to 2 decimal places, which can be overkill for VAWG purposes.

Different data types/sources may have different needs for this level of accuracy so can we make this an editable feature?

User story:
As a publisher, I want the ability to determine to how many decimal places (or only whole numbers) a figure is shown on sparkline dashboard tiles, so that I can have control over the accuracy and relevance of the data displayed on the homepage

**Comment by edd-harvey** [comment]
John to follow up with Dani before moving this issue on further
