### ISSUE TITLE
Make prototypes repository deployable

### ISSUE THREAD

**Issue by eldeal** [GSS-Cogs/dd-cms#866]
As we are creating a prototypes repo, it will need to be deployable to our environments.

- Create Dockerfile in GSS-Cogs/prototypes for React application
- Create a new [cloud build definition](https://github.com/GSS-Cogs/idpd-platform/blob/staging/environments/terraform/cloud_build_volto.tf) file, on the sandbox branch to be merged up through each environment
- Update nginx configuration to include a 'prototypes' subdomain
- Update [subsite variables](https://github.com/GSS-Cogs/idpd-platform/blob/staging/environments/terraform/vars/sandbox.tfvars#L21) to include "prototypes" for DNS routing

**Comment by JasonHowell** [comment]
This has been completed.
