### ISSUE TITLE
Investigate How to Update Logging Messages in Plone or SPARQL Data Connector

### ISSUE THREAD

**Issue by edd-harvey** [GSS-Cogs/dd-cms#884]
There is a lack of detail in CMS log messages

This issue is to investigate how to update logging messages in Plone or the SPARQL data connector and test the Plone log levels to see if the level should change

Tasks:

- [ ] Understand the [add-on](https://training.plone.org/mastering-plone-5/add-ons.html) architecture in Plone
- [ ] Identify whether the SPARQL Data Connector exists as code in the dd-cms repository we can change, or whether it is a dependency we pull in
- [ ] Prove your local environment outputs the [current logging](https://console.cloud.google.com/logs/query;query=resource.labels.cluster_name%3D%22staging%22%0Aresource.type%3D%22k8s_container%22;cursorTimestamp=2023-07-14T08:45:09.146203144Z;startTime=2023-07-14T08:45:00.000Z;endTime=2023-07-14T08:45:30.000Z?project=optimum-bonbon-257411) when loading charts (by loading a dashboard for example). Specifically, the only existing log line that mentions SPARQL is : `WARNING [eea.restapi:19][waitress-0] func:'_get_data' args:[(<ukstats.sparql_dataconnector.adapter.SPARQLDataProviderForConnectors object at 0x7fc590080250>,), {}] took: 0.7701 sec"`
- [ ] Find a way to log out some detail of the SPARQL query. This could be at the restapi layer, if the data connector code is out of our control, or preferably within the data connector add-on if possible. 
  - [ ] Ideally, we want to log the Title and SPARQL Endpoint URL from the data connector object

![Screenshot 2023-07-14 at 09 53 52](https://github.com/GSS-Cogs/dd-cms/assets/7114478/40bb517d-dc52-4bfa-9e8d-49b9fc0ef7dd)

**Comment by mikeAdamss** [comment]
@nimshi89 - Jenkins issue resolved, your PR has been merged.
