### ISSUE TITLE
Set Up Data Explorer Homepage Repo

### ISSUE THREAD

**Issue by edd-harvey** [GSS-Cogs/dd-cms#896]
Requirements:

- General:
  - [x] Repo name: `idpd-frontend-homepage`
  - [x] Create a description
  - [x] Automatically delete head branches: true
- Collaborators & Teams:
- [x] Teams: 'Office for National Statistics', Role: Admin
- Branches:
  - [x] Default branch: 'develop'
  - [x] Other branches: 'main' (there should be no 'master')
  - [x] Dismiss stale reviews: true (develop & main)
  - [x] Require reviews before merging: true (develop & main)
  - [x] Require GPG signatures on protected branches: true
  - [x] Restrict push to ONS team
![Screenshot 2023-06-19 at 14 38 50](https://github.com/GSS-Cogs/dd-cms/assets/7114478/dffa79a0-611b-487e-ba37-b1b5c5f05434)
![Screenshot 2023-06-19 at 14 39 04](https://github.com/GSS-Cogs/dd-cms/assets/7114478/c09ae72a-f4d8-4dd7-8861-9a33a2fee64d)

Our branch config should match that of the screenshots with the exception of the Team, which should be GSS-Cogs/Office for National Statistics

**Comment by StRhys** [comment]
https://github.com/GSS-Cogs/idpd-frontend-homepage
