### ISSUE TITLE
Testing the authentication

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#90]
We've wired up an OAuth2.0 based login using our Google domain, gsscogs.uk. Any domain member should be able to log in to the demo sites (after getting past the dreadful basic auth popups) and will then be registered as a user of the CMS, from where they can be given roles and permissions.

We need to test this out as there look to be some issues, potentially due to the separate basic-auth login.

Raise new issues as we find them.

**Comment by TahaRana97** [comment]
tested and works
