### ISSUE TITLE
Leave Quickly Button

### ISSUE THREAD

**Issue by edd-harvey** [GSS-Cogs/dd-cms#907]
### **Description**

A call to action button at top of every page for the VAWG site that say's leave quickly, and when the user clicks it they are redirected to another website (CC portal? ONS website? google?) 

### **User Need**

**As a** User of the VAWG site
**I want** a leave quickly button
**so that** I can leave the website immediately if I need to, without closing the browser

**Comment by eldeal** [comment]
Gov uk pattern for Exit a page: https://design-system.service.gov.uk/components/exit-this-page/
