### ISSUE TITLE
Volto Docker build needs refactoring

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#91]
The image is nearly 3GB and could do with using multi-stage build and better use of image layers so that e.g. `yarn develop` and `yarn install` only need to be run when package.json (& lockfile) change.

The `yarn test` step currently seems to overload our server.

**Comment by ajtucker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/GSS-Cogs/dd-cms/91?planning-poker) with ZenHub @cjfairchild @charlesons @rossbowen @TahaRana97 @osamede20

**Comment by ajtucker** [comment]
Fixed `yarn test` in Jenkins by #100.

Still to look at multi-stage build for the main Volto Docker images.

**Comment by ajtucker** [comment]
I've added some minor changes to https://github.com/GSS-Cogs/dd-cms/blob/volto-docker/volto/Dockerfile#L17 to get a multi-stage build that uses a similar approach to the test Dockerfile image.

The current issue is that the Razzle build (`yarn -s build` line) is meant to make a self-contained app in the build directory which can be run directly with `node ./server.js`, but there are still some external dependencies that haven't been bundled, e.g. `lodash` from the `govuk-react-jsx` package.

@nosnickid, this is probably one for you?

**Comment by cjfairchild** [comment]
I've done some minor tweaks to the Jenkinsfile and forced the pipeline to run in Jenkins - reducing run time and RAM utilisation significantly. It appears the HTML publishing plugin in Jenkins was attempting to archive all of the files in the build/test context in a heap in Java, which was causing OOM errors. 

See issue breanch ci-di for more.
